/**
 * Muslim Citation Timeline — Seed Dataset (24 Verified Slots / 3 Full Days)
 * Conforming strictly to Brief v02 Schema.
 * 
 * 8 Circadian Phases per day:
 * p1_dawn      (05:00 - 08:00) : Subuh / Fajar
 * p2_morning   (08:00 - 11:00) : Dhuha / Pagi Menjelang Siang
 * p3_noon      (11:00 - 14:00) : Siang Terik / Dzuhur
 * p4_afternoon (14:00 - 17:00) : Sore Hari / Ashar
 * p5_sunset    (17:00 - 19:00) : Senja / Maghrib
 * p6_evening   (19:00 - 22:00) : Malam Awal / Isya
 * p7_midnight  (22:00 - 02:00) : Tengah Malam / Qiyamul Lail
 * p8_predawn   (02:00 - 05:00) : Sepertiga Malam Terakhir / Tahajjud
 */

window.CITATIONS_DATA = [
  // ==========================================
  // DAY 1: 2026-10-04 (Yesterday)
  // ==========================================
  {
    id: "2026-10-04-p1",
    date: "2026-10-04",
    slot: 1,
    phase_id: "p1_dawn",
    phase_name_en: "Dawn / Fajr",
    phase_name_id: "Pagi / Fajar",
    time_range: "05:00-08:00",
    topic_en: "Morning Remembrance & Vitality",
    topic_id: "Dzikir Pagi dan Energi Kehidupan",
    source_type: "quran",
    arabic: "وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوعِ الشَّمْسِ وَقَبْلَ الْغُرُوبِ",
    text_en: "And glorify [Allah] with praise of your Lord before the rising of the sun and before its setting.",
    text_id: "Dan bertasbihlah dengan memuji Tuhanmu sebelum terbit matahari dan sebelum terbenamnya.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Welcoming the morning light through praise recalibrates the heart towards gratitude and purpose before engaging the busy world.",
    explain_id: "Menyambut fajar dengan tasbih menyelaraskan jiwa pada rasa syukur sebelum memasuki kesibukan dunia.",
    quran_detail: { surah_no: 50, surah_name: "Qaf", surah_name_ar: "ق", ayah: 39, juz: 26 },
    hadith_detail: null,
    source_url: "https://quran.com/50/39",
    tags: ["morning", "tasbih", "gratitude", "peace"]
  },
  {
    id: "2026-10-04-p2",
    date: "2026-10-04",
    slot: 2,
    phase_id: "p2_morning",
    phase_name_en: "Mid-Morning",
    phase_name_id: "Dhuha / Pagi Menjelang Siang",
    time_range: "08:00-11:00",
    topic_en: "Gratitude for the Joints of the Body",
    topic_id: "Sedekah Seluruh Persendian Tubuh",
    source_type: "hadith",
    arabic: "يُصْبِحُ عَلَى كُلِّ سُلاَمَى مِنْ أَحَدِكُمْ صَدَقَةٌ ... وَيُجْزِئُ مِنْ ذَلِكَ رَكْعَتَانِ يَرْكَعُهُمَا مِنَ الضُّحَى",
    text_en: "Charity is due each morning for every joint of your body... and two rak'ahs offered at Duha suffices for that.",
    text_id: "Setiap pagi, setiap persendian dari kalian wajib disedekahi... dan dua rakaat shalat Dhuha mencukupi semua itu.",
    translation_credit: "Sahih Muslim",
    explain_en: "Recognizing bodily health and mobility during the bustling hours of morning work by pausing for a brief spiritual reflection.",
    explain_id: "Kesehatan fisik di waktu produktif patut disyukuri melalui ketundukan dalam dua rakaat Dhuha.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "The Book of Prayer - Travellers",
      hadith_no: 720,
      narrator: "Abu Dharr (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:720",
    tags: ["duha", "health", "gratitude", "work"]
  },
  {
    id: "2026-10-04-p3",
    date: "2026-10-04",
    slot: 3,
    phase_id: "p3_noon",
    phase_name_en: "High Noon / Dhuhr",
    phase_name_id: "Siang Terik / Dzuhur",
    time_range: "11:00-14:00",
    topic_en: "The Midday Stand for Justice",
    topic_id: "Keadilan di Puncak Aktivitas",
    source_type: "quran",
    arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا كُونُوا قَوَّامِينَ بِالْقِسْطِ شُهَدَاءَ لِلَّهِ",
    text_en: "O you who have believed, be persistently standing firm in justice, witnesses for Allah.",
    text_id: "Wahai orang-orang yang beriman, jadilah kamu penegak keadilan, menjadi saksi karena Allah.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "At midday when commercial and interpersonal negotiations peak, ethical integrity must remain uncompromising.",
    explain_id: "Saat transaksi dan interaksi sosial mencapai puncaknya di siang hari, integritas moral harus tetap teguh.",
    quran_detail: { surah_no: 4, surah_name: "An-Nisa", surah_name_ar: "النساء", ayah: 135, juz: 5 },
    hadith_detail: null,
    source_url: "https://quran.com/4/135",
    tags: ["justice", "ethics", "integrity", "work"]
  },
  {
    id: "2026-10-04-p4",
    date: "2026-10-04",
    slot: 4,
    phase_id: "p4_afternoon",
    phase_name_en: "Late Afternoon / Asr",
    phase_name_id: "Sore Hari / Ashar",
    time_range: "14:00-17:00",
    topic_en: "Perseverance Across Finite Time",
    topic_id: "Kesabaran Mengarungi Waktu",
    source_type: "quran",
    arabic: "وَالْعَصْرِ • إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ • إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ",
    text_en: "By time, indeed mankind is in loss, except for those who have believed and done righteous deeds and advised each other to truth and patience.",
    text_id: "Demi masa, sungguh manusia berada dalam kerugian, kecuali orang-orang yang beriman dan mengerjakan kebajikan serta saling menasihati untuk kebenaran dan kesabaran.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "As the sun inclines and fatigue sets in, Surah Al-Asr reminds us that conscious action protects against the erosion of time.",
    explain_id: "Ketika matahari condong ke barat dan rasa lelah mendera, surat Al-Asr mengingatkan betapa berharganya sisa umur.",
    quran_detail: { surah_no: 103, surah_name: "Al-Asr", surah_name_ar: "العصر", ayah: 1, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/103/1-3",
    tags: ["time", "patience", "truth", "righteousness"]
  },
  {
    id: "2026-10-04-p5",
    date: "2026-10-04",
    slot: 5,
    phase_id: "p5_sunset",
    phase_name_en: "Sunset / Maghrib",
    phase_name_id: "Senja / Maghrib",
    time_range: "17:00-19:00",
    topic_en: "Twilight Pardon & Cleansing",
    topic_id: "Pengampunan di Waktu Senja",
    source_type: "hadith",
    arabic: "إِنَّ اللَّهَ تَعَالَى يَبْسُطُ يَدَهُ بِاللَّيْلِ لِيَتُوبَ مُسِيءُ النَّهَارِ",
    text_en: "Allah spreads out His Hand at night so that the one who sinned during the day may repent.",
    text_id: "Sesungguhnya Allah membentangkan tangan-Nya di malam hari agar orang yang berbuat dosa di siang hari bertaubat.",
    translation_credit: "Sahih Muslim",
    explain_en: "Sunset signals the closing of the diurnal ledger; an opportunity to release regrets and seek reconciliation with the Creator.",
    explain_id: "Senja menandai penutupan catatan siang hari; momen penuh kasih untuk melepaskan penyesalan dan kembali suci.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "The Book of Repentance",
      hadith_no: 2759,
      narrator: "Abu Musa Al-Ash'ari (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:2759",
    tags: ["sunset", "repentance", "mercy", "forgiveness"]
  },
  {
    id: "2026-10-04-p6",
    date: "2026-10-04",
    slot: 6,
    phase_id: "p6_evening",
    phase_name_en: "Early Night / Isha",
    phase_name_id: "Malam Awal / Isya",
    time_range: "19:00-22:00",
    topic_en: "Gathering and Harmony with Family",
    topic_id: "Kehangatan dan Kebaikan Keluarga",
    source_type: "hadith",
    arabic: "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ وَأَنَا خَيْرُكُمْ لِأَهْلِي",
    text_en: "The best of you are those who are best to their families, and I am the best among you to my family.",
    text_id: "Sebaik-baik kalian adalah yang terbaik terhadap keluarganya, dan aku adalah yang terbaik di antara kalian terhadap keluargaku.",
    translation_credit: "Jami' at-Tirmidhi",
    explain_en: "Evening is the hour of return to the domestic sanctuary, demanding patience, kindness, and attentiveness to loved ones.",
    explain_id: "Malam adalah saat kembali ke pelukan keluarga, waktu untuk menebar kelembutan dan perhatian tulus.",
    quran_detail: null,
    hadith_detail: {
      collection: "Jami' at-Tirmidhi",
      book: "Chapters on Virtues",
      hadith_no: 3895,
      narrator: "Aisha (RA)",
      grading: "Hasan Sahih (Good & Authentic)",
      grading_by: "At-Tirmidhi"
    },
    source_url: "https://sunnah.com/tirmidhi:3895",
    tags: ["family", "kindness", "evening", "character"]
  },
  {
    id: "2026-10-04-p7",
    date: "2026-10-04",
    slot: 7,
    phase_id: "p7_midnight",
    phase_name_en: "Midnight / Deep Night",
    phase_name_id: "Tengah Malam",
    time_range: "22:00-02:00",
    topic_en: "Stillness as God's Sign",
    topic_id: "Malam yang Tenang Sebagai Rahmat",
    source_type: "quran",
    arabic: "وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا • وَجَعَلْنَا اللَّيْلَ لِبَاسًا",
    text_en: "And made your sleep [a means for] rest, and made the night as clothing.",
    text_id: "Dan Kami menjadikan tidurmu untuk istirahat, dan Kami menjadikan malam sebagai pakaian.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Midnight veils the worldly clamor, allowing human biology and soul to enter restful sanctuary.",
    explain_id: "Malam menyelimuti bumi dengan kedamaian, memberi kesempatan bagi tubuh dan batin untuk beristirahat.",
    quran_detail: { surah_no: 78, surah_name: "An-Naba", surah_name_ar: "النبإ", ayah: 9, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/78/9-10",
    tags: ["night", "rest", "tranquility", "sleep"]
  },
  {
    id: "2026-10-04-p8",
    date: "2026-10-04",
    slot: 8,
    phase_id: "p8_predawn",
    phase_name_en: "Pre-Dawn / Tahajjud",
    phase_name_id: "Sepertiga Malam Terakhir",
    time_range: "02:00-05:00",
    topic_en: "Seeking Forgiveness at the Gate of Dawn",
    topic_id: "Istighfar di Waktu Sahur",
    source_type: "quran",
    arabic: "الصَّابِرِينَ وَالصَّادِقِينَ وَالْقَانِتِينَ وَالْمُنْفِقِينَ وَالْمُسْتَغْفِرِينَ بِالْأَسْحَارِ",
    text_en: "The patient, the true, the obedient, those who spend [in charity], and those who seek forgiveness before dawn.",
    text_id: "Yaitu orang-orang yang sabar, benar, taat, menginfakkan hartanya, dan memohon ampunan pada waktu sebelum fajar.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "In the silent depths of the third portion of night, supplication finds unhindered ascent.",
    explain_id: "Di kesunyian sepertiga malam terakhir, permohonan ampun memiliki kedudukan yang sangat istimewa.",
    quran_detail: { surah_no: 3, surah_name: "Ali 'Imran", surah_name_ar: "آل عمران", ayah: 17, juz: 3 },
    hadith_detail: null,
    source_url: "https://quran.com/3/17",
    tags: ["tahajjud", "predawn", "istighfar", "solitude"]
  },

  // ==========================================
  // DAY 2: 2026-10-05 (Today - Live Anchor)
  // ==========================================
  {
    id: "2026-10-05-p1",
    date: "2026-10-05",
    slot: 1,
    phase_id: "p1_dawn",
    phase_name_en: "Dawn / Fajr",
    phase_name_id: "Pagi / Fajar",
    time_range: "05:00-08:00",
    topic_en: "Gratitude at First Light",
    topic_id: "Syukur Menyambut Fajar",
    source_type: "quran",
    arabic: "وَالصُّبْحِ إِذَا تَنَفَّسَ",
    text_en: "And by the dawn when it breathes.",
    text_id: "Dan demi subuh apabila fajar mulai menyingsing.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "The dawn breathing is a sublime metaphor for the revitalisation of cosmic air, awakening the human soul to fresh mercy.",
    explain_id: "Subuh yang bernapas adalah metafora agung pembaruan energi alam semesta dan kesadaran ruhani yang bangkit kembali.",
    quran_detail: { surah_no: 81, surah_name: "At-Takwir", surah_name_ar: "التكوير", ayah: 18, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/81/18",
    tags: ["dawn", "nature", "awakening", "breath"]
  },
  {
    id: "2026-10-05-p2",
    date: "2026-10-05",
    slot: 2,
    phase_id: "p2_morning",
    phase_name_en: "Mid-Morning",
    phase_name_id: "Dhuha / Pagi Menjelang Siang",
    time_range: "08:00-11:00",
    topic_en: "Diligence & Ethical Sustenance",
    topic_id: "Etos Kerja dan Rezeki yang Halal",
    source_type: "hadith",
    arabic: "مَا أَكَلَ أَحَدٌ طَعَامًا قَطُّ خَيْرًا مِنْ أَنْ يَأْكُلَ مِنْ عَمَلِ يَدِهِ وَإِنَّ نَبِيَّ اللَّهِ دَاوُدَ عَلَيْهِ السَّلَام كَانَ يَأْكُلُ مِنْ عَمَلِ يَدِهِ",
    text_en: "No one has ever eaten better food than that which is earned by the work of his own hand, and the Prophet of Allah, David, used to eat from the work of his hands.",
    text_id: "Tidak ada seorang pun yang memakan makanan yang lebih baik daripada apa yang dihasilkan dari jerih payah tangannya sendiri. Dan sesungguhnya Nabi Allah Dawud 'alaihissalam makan dari hasil usahanya sendiri.",
    translation_credit: "Sahih al-Bukhari",
    explain_en: "Honest industry and self-reliance during the morning work hours are elevated into sacred forms of worship.",
    explain_id: "Kerja keras yang halal dan mandiri di waktu pagi diangkat derajatnya sebagai ibadah yang sangat mulia.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Book of Sales (Kitab al-Buyu)",
      hadith_no: 2072,
      narrator: "Al-Miqdam ibn Ma'dikarib (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Al-Bukhari"
    },
    source_url: "https://sunnah.com/bukhari:2072",
    tags: ["work", "sustenance", "integrity", "diligence"]
  },
  {
    id: "2026-10-05-p3",
    date: "2026-10-05",
    slot: 3,
    phase_id: "p3_noon",
    phase_name_en: "High Noon / Dhuhr",
    phase_name_id: "Siang Terik / Dzuhur",
    time_range: "11:00-14:00",
    topic_en: "The Pause for Remembrance Amidst Heat",
    topic_id: "Menjaga Salat di Tengah Terik",
    source_type: "quran",
    arabic: "حَافِظُوا عَلَى الصَّلَوَاتِ وَالصَّلَاةِ الْوُسْطَىٰ وَقُومُوا لِلَّهِ قَانِتِينَ",
    text_en: "Maintain with care the [obligatory] prayers and [in particular] the middle prayer and stand before Allah, devoutly obedient.",
    text_id: "Peliharalah semua salat dan salat wustha, dan laksanakanlah (salat) karena Allah dengan khusyuk.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "When the sun reaches its zenith and distraction runs high, prayer serves as a cool shade and spiritual anchor.",
    explain_id: "Ketika matahari tegak di puncaknya dan kesibukan dunia mendidih, salat menjadi naungan sejuk penyegar iman.",
    quran_detail: { surah_no: 2, surah_name: "Al-Baqarah", surah_name_ar: "البقرة", ayah: 238, juz: 2 },
    hadith_detail: null,
    source_url: "https://quran.com/2/238",
    tags: ["prayer", "dhuhr", "focus", "obedience"]
  },
  {
    id: "2026-10-05-p4",
    date: "2026-10-05",
    slot: 4,
    phase_id: "p4_afternoon",
    phase_name_en: "Late Afternoon / Asr",
    phase_name_id: "Sore Hari / Ashar",
    time_range: "14:00-17:00",
    topic_en: "Patience and Fortitude",
    topic_id: "Kesabaran dan Keberkahan Sore",
    source_type: "hadith",
    arabic: "مَنْ تَرَكَ صَلَاةَ الْعَصْرِ فَقَدْ حَبِطَ عَمَلُهُ",
    text_en: "Whoever neglects the Asr prayer, his good deeds will be void.",
    text_id: "Barangsiapa meninggalkan salat Ashar, maka terhapuslah amal kebaikannya.",
    translation_credit: "Sahih al-Bukhari",
    explain_en: "A stark admonition against losing vigilance as the workday winds down; finishing strong with mindful presence.",
    explain_id: "Peringatan tegas agar tidak terlena saat hari menjelang sore; menutup hari dengan kesadaran penuh.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Times of the Prayers",
      hadith_no: 553,
      narrator: "Buraida (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Al-Bukhari"
    },
    source_url: "https://sunnah.com/bukhari:553",
    tags: ["asr", "vigilance", "finish-strong", "discipline"]
  },
  {
    id: "2026-10-05-p5",
    date: "2026-10-05",
    slot: 5,
    phase_id: "p5_sunset",
    phase_name_en: "Sunset / Maghrib",
    phase_name_id: "Senja / Maghrib",
    time_range: "17:00-19:00",
    topic_en: "Gratitude for the Horizon",
    topic_id: "Keindahan Langit Senja dan Keagungan-Nya",
    source_type: "quran",
    arabic: "فَلَا أُقْسِمُ بِالشَّفَقِ • وَاللَّيْلِ وَمَا وَسَقَ • وَالْقَمَرِ إِذَا اتَّسَقَ",
    text_en: "So I swear by the twilight glow, and by the night and what it envelopes, and by the moon when it becomes full.",
    text_id: "Maka Aku bersumpah demi cahaya merah di waktu senja, demi malam dan apa yang diselubunginya, dan demi bulan apabila telah purnama.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "The transition from gold to indigo invokes contemplation on the transient stages through which human life constantly travels.",
    explain_id: "Pergeseran warna langit senja mengajak manusia merenungi tahapan kehidupan yang terus bergulir menuju keabadian.",
    quran_detail: { surah_no: 84, surah_name: "Al-Inshiqaq", surah_name_ar: "الانشقاق", ayah: 16, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/84/16-18",
    tags: ["sunset", "twilight", "reflection", "nature"]
  },
  {
    id: "2026-10-05-p6",
    date: "2026-10-05",
    slot: 6,
    phase_id: "p6_evening",
    phase_name_en: "Early Night / Isha",
    phase_name_id: "Malam Awal / Isya",
    time_range: "19:00-22:00",
    topic_en: "Kindness & Restful Speech",
    topic_id: "Tutur Kata yang Lembut di Malam Hari",
    source_type: "quran",
    arabic: "وَقُولُوا لِلنَّاسِ حُسْنًا",
    text_en: "And speak to people good [words].",
    text_id: "Dan bertutur-katalah yang baik kepada manusia.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "As conversations close the day, soft, gracious speech heals the friction gathered in daytime interactions.",
    explain_id: "Saat hari berakhir, tutur kata yang hangat dan penuh kebaikan merajut kembali harmoni sesama manusia.",
    quran_detail: { surah_no: 2, surah_name: "Al-Baqarah", surah_name_ar: "البقرة", ayah: 83, juz: 1 },
    hadith_detail: null,
    source_url: "https://quran.com/2/83",
    tags: ["speech", "gentleness", "community", "evening"]
  },
  {
    id: "2026-10-05-p7",
    date: "2026-10-05",
    slot: 7,
    phase_id: "p7_midnight",
    phase_name_en: "Midnight / Deep Night",
    phase_name_id: "Tengah Malam",
    time_range: "22:00-02:00",
    topic_en: "Supplication Before Sleeping",
    topic_id: "Menyerahkan Jiwa Menjelang Tidur",
    source_type: "hadith",
    arabic: "بِاسْمِكَ رَبِّ وَضَعْتُ جَنْبِي وَبِكَ أَرْفَعُهُ إِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ",
    text_en: "In Your name, my Lord, I lay down my side and in Your name I raise it. If You hold my soul, have mercy upon it, and if You release it, protect it as You protect Your righteous slaves.",
    text_id: "Dengan nama-Mu wahai Tuhanku, aku meletakkan lambungku dan dengan nama-Mu aku mengangkatnya. Jika Engkau menahan jiwaku maka kasihanilah, dan jika Engkau melepaskannya maka jagalah sebagaimana Engkau menjaga hamba-hamba-Mu yang saleh.",
    translation_credit: "Sahih al-Bukhari & Muslim",
    explain_en: "Sleep is the minor transition of consciousness; surrendering the soul to divine custody yields untroubled serenity.",
    explain_id: "Tidur adalah pasrah total; mempercayakan jiwa pada penjagaan Ilahi menghadirkan kedamaian tanpa rasa takut.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Book of Invocations",
      hadith_no: 6320,
      narrator: "Abu Hurairah (RA)",
      grading: "Sahih (Muttafaqun 'Alayh)",
      grading_by: "Al-Bukhari & Muslim"
    },
    source_url: "https://sunnah.com/bukhari:6320",
    tags: ["sleep", "surrender", "trust", "midnight"]
  },
  {
    id: "2026-10-05-p8",
    date: "2026-10-05",
    slot: 8,
    phase_id: "p8_predawn",
    phase_name_en: "Pre-Dawn / Tahajjud",
    phase_name_id: "Sepertiga Malam Terakhir",
    time_range: "02:00-05:00",
    topic_en: "The Divine Descent & Answered Prayers",
    topic_id: "Turunnya Rahmat di Sepertiga Malam",
    source_type: "hadith",
    arabic: "يَنْزِلُ رَبُّنَا تَبَارَكَ وَتَعَالَى كُلَّ لَيْلَةٍ إِلَى السَّمَاءِ الدُّنْيَا حِينَ يَبْقَى ثُلُثُ اللَّيْلِ الآخِرُ يَقُولُ مَنْ يَدْعُونِي فَأَسْتَجِيبَ لَهُ مَنْ يَسْأَلُنِي فَأُعْطِيَهُ مَنْ يَسْتَغْفِرُنِي فَأَغْفِرَ لَهُ",
    text_en: "Our Lord, Blessed and Exalted, descends each night to the lowest heaven when the last third of the night remains, saying: 'Who calls upon Me that I may answer him? Who asks of Me that I may give him? Who seeks My forgiveness that I may forgive him?'",
    text_id: "Tuhan kita Tabaraka wa Ta'ala turun setiap malam ke langit dunia pada sepertiga malam terakhir, seraya berfirman: 'Siapa yang berdoa kepada-Ku niscaya Aku kabulkan, siapa yang meminta kepada-Ku niscaya Aku beri, dan siapa yang memohon ampun kepada-Ku niscaya Aku ampuni.'",
    translation_credit: "Sahih al-Bukhari & Muslim",
    explain_en: "The most intimate station of human-divine communion, where sincerity is unadulterated by any spectators.",
    explain_id: "Puncak keintiman seorang hamba dengan Tuhannya, di mana doa dipanjatkan murni tanpa riya.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Book of Tahajjud (Night Prayer)",
      hadith_no: 1145,
      narrator: "Abu Hurairah (RA)",
      grading: "Sahih (Muttafaqun 'Alayh)",
      grading_by: "Al-Bukhari & Muslim"
    },
    source_url: "https://sunnah.com/bukhari:1145",
    tags: ["tahajjud", "dua", "forgiveness", "mercy"]
  },

  // ==========================================
  // DAY 3: 2026-10-06 (Tomorrow)
  // ==========================================
  {
    id: "2026-10-06-p1",
    date: "2026-10-06",
    slot: 1,
    phase_id: "p1_dawn",
    phase_name_en: "Dawn / Fajr",
    phase_name_id: "Pagi / Fajar",
    time_range: "05:00-08:00",
    topic_en: "The Weight of the Two Rak'ahs of Dawn",
    topic_id: "Dua Rakaat Sebelum Fajar",
    source_type: "hadith",
    arabic: "رَكْعَتَا الْفَجْرِ خَيْرٌ مِنَ الدُّنْيَا وَمَا فِيهَا",
    text_en: "The two rak'ahs before dawn are better than the entire world and everything within it.",
    text_id: "Dua rakaat (sebelum) subuh lebih baik daripada dunia beserta seluruh isinya.",
    translation_credit: "Sahih Muslim",
    explain_en: "A striking recalibration of value: the inner wealth of conscious prayer outweighs all material wealth.",
    explain_id: "Menimbang kembali hakikat nilai: ketenangan spiritual jauh melampaui seluruh perhiasan materi dunia.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "The Book of Prayer - Travellers",
      hadith_no: 725,
      narrator: "Aisha (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:725",
    tags: ["fajr", "sunnah", "wealth", "perspective"]
  },
  {
    id: "2026-10-06-p2",
    date: "2026-10-06",
    slot: 2,
    phase_id: "p2_morning",
    phase_name_en: "Mid-Morning",
    phase_name_id: "Dhuha / Pagi Menjelang Siang",
    time_range: "08:00-11:00",
    topic_en: "Trust in Divine Provision",
    topic_id: "Tawakal Seperti Burung di Pagi Hari",
    source_type: "hadith",
    arabic: "لَوْ أَنَّكُمْ تَوَكَّلُونَ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرَزَقَكُمْ كَمَا يَرْزُقُ الطَّيْرَ تَغْدُو خِمَاصًا وَتَرُوحُ بِطَانًا",
    text_en: "If you were to rely upon Allah with true reliance, He would provide for you just as He provides for the birds: they go out in the morning hungry and return full.",
    text_id: "Seandainya kalian bertawakal kepada Allah dengan sebenar-benar tawakal, niscaya Dia akan memberi rezeki sebagaimana burung: pergi di pagi hari dalam keadaan lapar dan pulang di sore hari dengan kenyang.",
    translation_credit: "Jami' at-Tirmidhi",
    explain_en: "True reliance is active, not passive. The bird leaves its nest at dawn to seek food, demonstrating faith joined with vigorous effort.",
    explain_id: "Tawakal sejati bukanlah berdiam diri. Burung mengepakkan sayap keluar sarang di pagi hari, memadukan iman dengan ikhtiar nyata.",
    quran_detail: null,
    hadith_detail: {
      collection: "Jami' at-Tirmidhi",
      book: "Chapters on Zuhd",
      hadith_no: 2344,
      narrator: "Umar ibn Al-Khattab (RA)",
      grading: "Hasan Sahih (Good & Authentic)",
      grading_by: "At-Tirmidhi"
    },
    source_url: "https://sunnah.com/tirmidhi:2344",
    tags: ["tawakkul", "provision", "effort", "morning"]
  },
  {
    id: "2026-10-06-p3",
    date: "2026-10-06",
    slot: 3,
    phase_id: "p3_noon",
    phase_name_en: "High Noon / Dhuhr",
    phase_name_id: "Siang Terik / Dzuhur",
    time_range: "11:00-14:00",
    topic_en: "Humility Amidst Power",
    topic_id: "Kerendahan Hati di Puncak Kejayaan",
    source_type: "quran",
    arabic: "وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا إِنَّكَ لَنْ تَخْرِقَ الْأَرْضَ وَلَنْ تَبْلُغَ الْجِبَالَ طُولًا",
    text_en: "And do not walk upon the earth exultantly. Indeed, you will never tear the earth [apart], and you will never reach the mountains in height.",
    text_id: "Dan janganlah engkau berjalan di bumi ini dengan sombong, karena sesungguhnya engkau tidak akan dapat menembus bumi dan tidak akan mencapai tinggi gunung.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Reminding human beings of their fragility precisely when accomplishments tempt arrogance during peak hours.",
    explain_id: "Mengingatkan kembali kerapuhan manusia justru di saat pencapaian duniawi menggoda lahirnya kesombongan.",
    quran_detail: { surah_no: 17, surah_name: "Al-Isra", surah_name_ar: "الإسراء", ayah: 37, juz: 15 },
    hadith_detail: null,
    source_url: "https://quran.com/17/37",
    tags: ["humility", "character", "perspective", "wisdom"]
  },
  {
    id: "2026-10-06-p4",
    date: "2026-10-06",
    slot: 4,
    phase_id: "p4_afternoon",
    phase_name_en: "Late Afternoon / Asr",
    phase_name_id: "Sore Hari / Ashar",
    time_range: "14:00-17:00",
    topic_en: "The Shadow and Divine Proportion",
    topic_id: "Bayangan Sore yang Merunduk",
    source_type: "quran",
    arabic: "أَلَمْ تَرَ إِلَىٰ رَبِّكَ كَيْفَ مَدَّ الظِّلَّ وَلَوْ شَاءَ لَجَعَلَهُ سَاكِنًا",
    text_en: "Have you not considered your Lord - how He extends the shadow? And if He willed, He could have made it stationary.",
    text_id: "Tidakkah engkau memperhatikan (penciptaan) Tuhanmu, bagaimana Dia memanjangkan bayang-bayang? Sekiranya Dia menghendaki, niscaya Dia menjadikannya tetap.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "The lengthening afternoon shadow is an astronomical witness to cosmic order, prompting meditative gratitude.",
    explain_id: "Memanjangnya bayang-bayang di waktu sore adalah bukti keteraturan kosmos yang mengundang kekaguman pada Sang Pencipta.",
    quran_detail: { surah_no: 25, surah_name: "Al-Furqan", surah_name_ar: "الفرقان", ayah: 45, juz: 19 },
    hadith_detail: null,
    source_url: "https://quran.com/25/45",
    tags: ["nature", "afternoon", "cosmology", "reflection"]
  },
  {
    id: "2026-10-06-p5",
    date: "2026-10-06",
    slot: 5,
    phase_id: "p5_sunset",
    phase_name_en: "Sunset / Maghrib",
    phase_name_id: "Senja / Maghrib",
    time_range: "17:00-19:00",
    topic_en: "Protection at Nightfall",
    topic_id: "Doa Perlindungan Menjelang Petang",
    source_type: "hadith",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ",
    text_en: "We have reached the evening and the kingdom belongs to Allah, and all praise is for Allah; none has the right to be worshipped except Allah alone, without partner.",
    text_id: "Kami telah memasuki waktu petang dan kerajaan ini milik Allah, segala puji bagi Allah, tidak ada Tuhan selain Allah semata yang tiada sekutu bagi-Nya.",
    translation_credit: "Sahih Muslim",
    explain_en: "Pronouncing the evening invocation aligns one's awareness as day surrenders its light to the night sky.",
    explain_id: "Membaca dzikir petang menenangkan hati saat peralihan terang menjadi gelap.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "Book of Prayers & Remembrances",
      hadith_no: 2723,
      narrator: "Abdullah ibn Mas'ud (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:2723",
    tags: ["sunset", "evening-adhkar", "surrender", "sovereignty"]
  },
  {
    id: "2026-10-06-p6",
    date: "2026-10-06",
    slot: 6,
    phase_id: "p6_evening",
    phase_name_en: "Early Night / Isha",
    phase_name_id: "Malam Awal / Isya",
    time_range: "19:00-22:00",
    topic_en: "Purity of Heart Towards All",
    topic_id: "Kebersihan Hati Sebelum Pejam",
    source_type: "hadith",
    arabic: "لاَ تَبَاغَضُوا وَلاَ تَحَاسَدُوا وَلاَ تَدَابَرُوا وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا",
    text_en: "Do not hate one another, do not envy one another, do not turn away from one another, but be, O servants of Allah, brothers.",
    text_id: "Janganlah kalian saling membenci, saling mendengki, dan saling membelakangi. Jadilah kalian hamba-hamba Allah yang bersaudara.",
    translation_credit: "Sahih al-Bukhari & Muslim",
    explain_en: "Releasing malice, grudge, and competitive friction before nightfall grants wholesome sleep and clean conscience.",
    explain_id: "Membuang rasa benci dan dengki sebelum terlelap menghasilkan tidur yang berkualitas dan hati yang lapang.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Good Manners and Form (Al-Adab)",
      hadith_no: 6065,
      narrator: "Anas ibn Malik (RA)",
      grading: "Sahih (Muttafaqun 'Alayh)",
      grading_by: "Al-Bukhari & Muslim"
    },
    source_url: "https://sunnah.com/bukhari:6065",
    tags: ["brotherhood", "purity", "forgiveness", "night"]
  },
  {
    id: "2026-10-06-p7",
    date: "2026-10-06",
    slot: 7,
    phase_id: "p7_midnight",
    phase_name_en: "Midnight / Deep Night",
    phase_name_id: "Tengah Malam",
    time_range: "22:00-02:00",
    topic_en: "The Quiet Majesty of Heaven",
    topic_id: "Merenungi Bintang di Tengah Malam",
    source_type: "quran",
    arabic: "إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِأُولِي الْأَلْبَابِ",
    text_en: "Indeed, in the creation of the heavens and the earth and the alternation of the night and the day are signs for those of understanding.",
    text_id: "Sesungguhnya dalam penciptaan langit dan bumi, dan silih bergantinya malam dan siang terdapat tanda-tanda bagi orang-orang yang berakal.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Midnight contemplation of celestial order expands perspective beyond fleeting temporal troubles.",
    explain_id: "Renungan tengah malam atas luasnya langit melonggarkan himpitan masalah duniawi yang fana.",
    quran_detail: { surah_no: 3, surah_name: "Ali 'Imran", surah_name_ar: "آل عمران", ayah: 190, juz: 4 },
    hadith_detail: null,
    source_url: "https://quran.com/3/190",
    tags: ["night", "intellect", "creation", "universe"]
  },
  {
    id: "2026-10-06-p8",
    date: "2026-10-06",
    slot: 8,
    phase_id: "p8_predawn",
    phase_name_en: "Pre-Dawn / Tahajjud",
    phase_name_id: "Sepertiga Malam Terakhir",
    time_range: "02:00-05:00",
    topic_en: "The Night Prayer as the Ornament of the Righteous",
    topic_id: "Salat Malam Lambang Kehormatan Mukmin",
    source_type: "hadith",
    arabic: "عَلَيْكُمْ بِقِيَامِ اللَّيْلِ فَإِنَّهُ دَأْبُ الصَّالِحِينَ قَبْلَكُمْ وَقُرْبَةٌ إِلَى اللَّهِ تَعَالَى وَمَنْهَاةٌ عَنِ الإِثْمِ",
    text_en: "Hold fast to the night prayer, for it was the habit of the righteous before you, a means of drawing close to Allah, and a shield against sin.",
    text_id: "Hendaklah kalian mendirikan salat malam, karena itu adalah kebiasaan orang-orang saleh sebelum kalian, sarana mendekatkan diri kepada Allah, dan penghapus dosa.",
    translation_credit: "Jami' at-Tirmidhi",
    explain_en: "Pre-dawn vigil builds internal fortitude and moral stamina that guards against spiritual decay throughout the coming day.",
    explain_id: "Salat malam membentuk ketahanan batin dan imunitas moral yang membentengi diri sepanjang hari berikutnya.",
    quran_detail: null,
    hadith_detail: {
      collection: "Jami' at-Tirmidhi",
      book: "Chapters on Invocations",
      hadith_no: 3549,
      narrator: "Abu Umamah (RA)",
      grading: "Hasan (Good)",
      grading_by: "Al-Albani / At-Tirmidhi"
    },
    source_url: "https://sunnah.com/tirmidhi:3549",
    tags: ["tahajjud", "vigil", "character", "predawn"]
  }
];

// Phase metadata dictionary
window.PHASES_CONFIG = [
  { id: "p1_dawn", slot: 1, name_en: "Dawn / Fajr", name_id: "Pagi / Fajar", range: "05:00-08:00", startHour: 5, endHour: 8, color: "hsl(42, 92%, 55%)", icon: "🌅" },
  { id: "p2_morning", slot: 2, name_en: "Mid-Morning", name_id: "Dhuha / Menjelang Siang", range: "08:00-11:00", startHour: 8, endHour: 11, color: "hsl(48, 96%, 53%)", icon: "☀️" },
  { id: "p3_noon", slot: 3, name_en: "High Noon / Dhuhr", name_id: "Siang Terik / Dzuhur", range: "11:00-14:00", startHour: 11, endHour: 14, color: "hsl(198, 88%, 48%)", icon: "🌞" },
  { id: "p4_afternoon", slot: 4, name_en: "Late Afternoon / Asr", name_id: "Sore Hari / Ashar", range: "14:00-17:00", startHour: 14, endHour: 17, color: "hsl(24, 85%, 52%)", icon: "🌤️" },
  { id: "p5_sunset", slot: 5, name_en: "Sunset / Maghrib", name_id: "Senja / Maghrib", range: "17:00-19:00", startHour: 17, endHour: 19, color: "hsl(340, 75%, 56%)", icon: "🌇" },
  { id: "p6_evening", slot: 6, name_en: "Early Night / Isha", name_id: "Malam Awal / Isya", range: "19:00-22:00", startHour: 19, endHour: 22, color: "hsl(228, 62%, 54%)", icon: "🌌" },
  { id: "p7_midnight", slot: 7, name_en: "Midnight / Deep Night", name_id: "Tengah Malam", range: "22:00-02:00", startHour: 22, endHour: 2, color: "hsl(265, 50%, 48%)", icon: "🌙" },
  { id: "p8_predawn", slot: 8, name_en: "Pre-Dawn / Tahajjud", name_id: "Sepertiga Malam Terakhir", range: "02:00-05:00", startHour: 2, endHour: 5, color: "hsl(182, 70%, 46%)", icon: "✨" }
];
