/**
 * Muslim Citation Timeline — Seed Dataset (24 Verified Slots / 3 Full Days)
 * Conforming strictly to Brief v02 Schema.
 * 
 * 8 Circadian Phases per day:
 * p1_dawn      (05:00 - 08:00) : Subuh / Fajar
 * p2_morning   (08:00 - 11:00) : Dhuha / Pagi Menjelang Siang
 * p3_noon      (11:00 - 14:00) : Siang Terik / Dzuhur
 * p4_afternoon (14:00 - 17:00) : Sore Hari / Ashar
 * p5_sunset    (17:00 - 19:00) : Senja / Maghrib
 * p6_evening   (19:00 - 22:00) : Malam Awal / Isya
 * p7_midnight  (22:00 - 02:00) : Tengah Malam / Qiyamul Lail
 * p8_predawn   (02:00 - 05:00) : Sepertiga Malam Terakhir / Tahajjud
 */

window.CITATIONS_DATA = [
  // ==========================================
  // DAY 1: 2026-10-04 (Yesterday)
  // ==========================================
  {
    id: "2026-10-04-p1",
    date: "2026-10-04",
    slot: 1,
    phase_id: "p1_dawn",
    phase_name_en: "Dawn / Fajr",
    phase_name_id: "Pagi / Fajar",
    time_range: "05:00-08:00",
    topic_en: "Morning Remembrance & Vitality",
    topic_id: "Dzikir Pagi dan Energi Kehidupan",
    source_type: "quran",
    arabic: "وَسَبِّحْ بِحَمْدِ رَبِّكَ قَبْلَ طُلُوعِ الشَّمْسِ وَقَبْلَ الْغُرُوبِ",
    text_en: "And glorify [Allah] with praise of your Lord before the rising of the sun and before its setting.",
    text_id: "Dan bertasbihlah dengan memuji Tuhanmu sebelum terbit matahari dan sebelum terbenamnya.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Welcoming the morning light through praise recalibrates the heart towards gratitude and purpose before engaging the busy world.",
    explain_id: "Menyambut fajar dengan tasbih menyelaraskan jiwa pada rasa syukur sebelum memasuki kesibukan dunia.",
    quran_detail: { surah_no: 50, surah_name: "Qaf", surah_name_ar: "ق", ayah: 39, juz: 26 },
    hadith_detail: null,
    source_url: "https://quran.com/50/39",
    tags: ["morning", "tasbih", "gratitude", "peace"]
  },
  {
    id: "2026-10-04-p2",
    date: "2026-10-04",
    slot: 2,
    phase_id: "p2_morning",
    phase_name_en: "Mid-Morning",
    phase_name_id: "Dhuha / Pagi Menjelang Siang",
    time_range: "08:00-11:00",
    topic_en: "Gratitude for the Joints of the Body",
    topic_id: "Sedekah Seluruh Persendian Tubuh",
    source_type: "hadith",
    arabic: "يُصْبِحُ عَلَى كُلِّ سُلاَمَى مِنْ أَحَدِكُمْ صَدَقَةٌ ... وَيُجْزِئُ مِنْ ذَلِكَ رَكْعَتَانِ يَرْكَعُهُمَا مِنَ الضُّحَى",
    text_en: "Charity is due each morning for every joint of your body... and two rak'ahs offered at Duha suffices for that.",
    text_id: "Setiap pagi, setiap persendian dari kalian wajib disedekahi... dan dua rakaat shalat Dhuha mencukupi semua itu.",
    translation_credit: "Sahih Muslim",
    explain_en: "Recognizing bodily health and mobility during the bustling hours of morning work by pausing for a brief spiritual reflection.",
    explain_id: "Kesehatan fisik di waktu produktif patut disyukuri melalui ketundukan dalam dua rakaat Dhuha.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "The Book of Prayer - Travellers",
      hadith_no: 720,
      narrator: "Abu Dharr (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:720",
    tags: ["duha", "health", "gratitude", "work"]
  },
  {
    id: "2026-10-04-p3",
    date: "2026-10-04",
    slot: 3,
    phase_id: "p3_noon",
    phase_name_en: "High Noon / Dhuhr",
    phase_name_id: "Siang Terik / Dzuhur",
    time_range: "11:00-14:00",
    topic_en: "The Midday Stand for Justice",
    topic_id: "Keadilan di Puncak Aktivitas",
    source_type: "quran",
    arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا كُونُوا قَوَّامِينَ بِالْقِسْطِ شُهَدَاءَ لِلَّهِ",
    text_en: "O you who have believed, be persistently standing firm in justice, witnesses for Allah.",
    text_id: "Wahai orang-orang yang beriman, jadilah kamu penegak keadilan, menjadi saksi karena Allah.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "At midday when commercial and interpersonal negotiations peak, ethical integrity must remain uncompromising.",
    explain_id: "Saat transaksi dan interaksi sosial mencapai puncaknya di siang hari, integritas moral harus tetap teguh.",
    quran_detail: { surah_no: 4, surah_name: "An-Nisa", surah_name_ar: "النساء", ayah: 135, juz: 5 },
    hadith_detail: null,
    source_url: "https://quran.com/4/135",
    tags: ["justice", "ethics", "integrity", "work"]
  },
  {
    id: "2026-10-04-p4",
    date: "2026-10-04",
    slot: 4,
    phase_id: "p4_afternoon",
    phase_name_en: "Late Afternoon / Asr",
    phase_name_id: "Sore Hari / Ashar",
    time_range: "14:00-17:00",
    topic_en: "Perseverance Across Finite Time",
    topic_id: "Kesabaran Mengarungi Waktu",
    source_type: "quran",
    arabic: "وَالْعَصْرِ • إِنَّ الْإِنْسَانَ لَفِي خُسْرٍ • إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ",
    text_en: "By time, indeed mankind is in loss, except for those who have believed and done righteous deeds and advised each other to truth and patience.",
    text_id: "Demi masa, sungguh manusia berada dalam kerugian, kecuali orang-orang yang beriman dan mengerjakan kebajikan serta saling menasihati untuk kebenaran dan kesabaran.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "As the sun inclines and fatigue sets in, Surah Al-Asr reminds us that conscious action protects against the erosion of time.",
    explain_id: "Ketika matahari condong ke barat dan rasa lelah mendera, surat Al-Asr mengingatkan betapa berharganya sisa umur.",
    quran_detail: { surah_no: 103, surah_name: "Al-Asr", surah_name_ar: "العصر", ayah: 1, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/103/1-3",
    tags: ["time", "patience", "truth", "righteousness"]
  },
  {
    id: "2026-10-04-p5",
    date: "2026-10-04",
    slot: 5,
    phase_id: "p5_sunset",
    phase_name_en: "Sunset / Maghrib",
    phase_name_id: "Senja / Maghrib",
    time_range: "17:00-19:00",
    topic_en: "Twilight Pardon & Cleansing",
    topic_id: "Pengampunan di Waktu Senja",
    source_type: "hadith",
    arabic: "إِنَّ اللَّهَ تَعَالَى يَبْسُطُ يَدَهُ بِاللَّيْلِ لِيَتُوبَ مُسِيءُ النَّهَارِ",
    text_en: "Allah spreads out His Hand at night so that the one who sinned during the day may repent.",
    text_id: "Sesungguhnya Allah membentangkan tangan-Nya di malam hari agar orang yang berbuat dosa di siang hari bertaubat.",
    translation_credit: "Sahih Muslim",
    explain_en: "Sunset signals the closing of the diurnal ledger; an opportunity to release regrets and seek reconciliation with the Creator.",
    explain_id: "Senja menandai penutupan catatan siang hari; momen penuh kasih untuk melepaskan penyesalan dan kembali suci.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "The Book of Repentance",
      hadith_no: 2759,
      narrator: "Abu Musa Al-Ash'ari (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:2759",
    tags: ["sunset", "repentance", "mercy", "forgiveness"]
  },
  {
    id: "2026-10-04-p6",
    date: "2026-10-04",
    slot: 6,
    phase_id: "p6_evening",
    phase_name_en: "Early Night / Isha",
    phase_name_id: "Malam Awal / Isya",
    time_range: "19:00-22:00",
    topic_en: "Gathering and Harmony with Family",
    topic_id: "Kehangatan dan Kebaikan Keluarga",
    source_type: "hadith",
    arabic: "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ وَأَنَا خَيْرُكُمْ لِأَهْلِي",
    text_en: "The best of you are those who are best to their families, and I am the best among you to my family.",
    text_id: "Sebaik-baik kalian adalah yang terbaik terhadap keluarganya, dan aku adalah yang terbaik di antara kalian terhadap keluargaku.",
    translation_credit: "Jami' at-Tirmidhi",
    explain_en: "Evening is the hour of return to the domestic sanctuary, demanding patience, kindness, and attentiveness to loved ones.",
    explain_id: "Malam adalah saat kembali ke pelukan keluarga, waktu untuk menebar kelembutan dan perhatian tulus.",
    quran_detail: null,
    hadith_detail: {
      collection: "Jami' at-Tirmidhi",
      book: "Chapters on Virtues",
      hadith_no: 3895,
      narrator: "Aisha (RA)",
      grading: "Hasan Sahih (Good & Authentic)",
      grading_by: "At-Tirmidhi"
    },
    source_url: "https://sunnah.com/tirmidhi:3895",
    tags: ["family", "kindness", "evening", "character"]
  },
  {
    id: "2026-10-04-p7",
    date: "2026-10-04",
    slot: 7,
    phase_id: "p7_midnight",
    phase_name_en: "Midnight / Deep Night",
    phase_name_id: "Tengah Malam",
    time_range: "22:00-02:00",
    topic_en: "Stillness as God's Sign",
    topic_id: "Malam yang Tenang Sebagai Rahmat",
    source_type: "quran",
    arabic: "وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا • وَجَعَلْنَا اللَّيْلَ لِبَاسًا",
    text_en: "And made your sleep [a means for] rest, and made the night as clothing.",
    text_id: "Dan Kami menjadikan tidurmu untuk istirahat, dan Kami menjadikan malam sebagai pakaian.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Midnight veils the worldly clamor, allowing human biology and soul to enter restful sanctuary.",
    explain_id: "Malam menyelimuti bumi dengan kedamaian, memberi kesempatan bagi tubuh dan batin untuk beristirahat.",
    quran_detail: { surah_no: 78, surah_name: "An-Naba", surah_name_ar: "النبإ", ayah: 9, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/78/9-10",
    tags: ["night", "rest", "tranquility", "sleep"]
  },
  {
    id: "2026-10-04-p8",
    date: "2026-10-04",
    slot: 8,
    phase_id: "p8_predawn",
    phase_name_en: "Pre-Dawn / Tahajjud",
    phase_name_id: "Sepertiga Malam Terakhir",
    time_range: "02:00-05:00",
    topic_en: "Seeking Forgiveness at the Gate of Dawn",
    topic_id: "Istighfar di Waktu Sahur",
    source_type: "quran",
    arabic: "الصَّابِرِينَ وَالصَّادِقِينَ وَالْقَانِتِينَ وَالْمُنْفِقِينَ وَالْمُسْتَغْفِرِينَ بِالْأَسْحَارِ",
    text_en: "The patient, the true, the obedient, those who spend [in charity], and those who seek forgiveness before dawn.",
    text_id: "Yaitu orang-orang yang sabar, benar, taat, menginfakkan hartanya, dan memohon ampunan pada waktu sebelum fajar.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "In the silent depths of the third portion of night, supplication finds unhindered ascent.",
    explain_id: "Di kesunyian sepertiga malam terakhir, permohonan ampun memiliki kedudukan yang sangat istimewa.",
    quran_detail: { surah_no: 3, surah_name: "Ali 'Imran", surah_name_ar: "آل عمران", ayah: 17, juz: 3 },
    hadith_detail: null,
    source_url: "https://quran.com/3/17",
    tags: ["tahajjud", "predawn", "istighfar", "solitude"]
  },

  // ==========================================
  // DAY 2: 2026-10-05 (Today - Live Anchor)
  // ==========================================
  {
    id: "2026-10-05-p1",
    date: "2026-10-05",
    slot: 1,
    phase_id: "p1_dawn",
    phase_name_en: "Dawn / Fajr",
    phase_name_id: "Pagi / Fajar",
    time_range: "05:00-08:00",
    topic_en: "Gratitude at First Light",
    topic_id: "Syukur Menyambut Fajar",
    source_type: "quran",
    arabic: "وَالصُّبْحِ إِذَا تَنَفَّسَ",
    text_en: "And by the dawn when it breathes.",
    text_id: "Dan demi subuh apabila fajar mulai menyingsing.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "The dawn breathing is a sublime metaphor for the revitalisation of cosmic air, awakening the human soul to fresh mercy.",
    explain_id: "Subuh yang bernapas adalah metafora agung pembaruan energi alam semesta dan kesadaran ruhani yang bangkit kembali.",
    quran_detail: { surah_no: 81, surah_name: "At-Takwir", surah_name_ar: "التكوير", ayah: 18, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/81/18",
    tags: ["dawn", "nature", "awakening", "breath"]
  },
  {
    id: "2026-10-05-p2",
    date: "2026-10-05",
    slot: 2,
    phase_id: "p2_morning",
    phase_name_en: "Mid-Morning",
    phase_name_id: "Dhuha / Pagi Menjelang Siang",
    time_range: "08:00-11:00",
    topic_en: "Diligence & Ethical Sustenance",
    topic_id: "Etos Kerja dan Rezeki yang Halal",
    source_type: "hadith",
    arabic: "مَا أَكَلَ أَحَدٌ طَعَامًا قَطُّ خَيْرًا مِنْ أَنْ يَأْكُلَ مِنْ عَمَلِ يَدِهِ وَإِنَّ نَبِيَّ اللَّهِ دَاوُدَ عَلَيْهِ السَّلَام كَانَ يَأْكُلُ مِنْ عَمَلِ يَدِهِ",
    text_en: "No one has ever eaten better food than that which is earned by the work of his own hand, and the Prophet of Allah, David, used to eat from the work of his hands.",
    text_id: "Tidak ada seorang pun yang memakan makanan yang lebih baik daripada apa yang dihasilkan dari jerih payah tangannya sendiri. Dan sesungguhnya Nabi Allah Dawud 'alaihissalam makan dari hasil usahanya sendiri.",
    translation_credit: "Sahih al-Bukhari",
    explain_en: "Honest industry and self-reliance during the morning work hours are elevated into sacred forms of worship.",
    explain_id: "Kerja keras yang halal dan mandiri di waktu pagi diangkat derajatnya sebagai ibadah yang sangat mulia.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Book of Sales (Kitab al-Buyu)",
      hadith_no: 2072,
      narrator: "Al-Miqdam ibn Ma'dikarib (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Al-Bukhari"
    },
    source_url: "https://sunnah.com/bukhari:2072",
    tags: ["work", "sustenance", "integrity", "diligence"]
  },
  {
    id: "2026-10-05-p3",
    date: "2026-10-05",
    slot: 3,
    phase_id: "p3_noon",
    phase_name_en: "High Noon / Dhuhr",
    phase_name_id: "Siang Terik / Dzuhur",
    time_range: "11:00-14:00",
    topic_en: "The Pause for Remembrance Amidst Heat",
    topic_id: "Menjaga Salat di Tengah Terik",
    source_type: "quran",
    arabic: "حَافِظُوا عَلَى الصَّلَوَاتِ وَالصَّلَاةِ الْوُسْطَىٰ وَقُومُوا لِلَّهِ قَانِتِينَ",
    text_en: "Maintain with care the [obligatory] prayers and [in particular] the middle prayer and stand before Allah, devoutly obedient.",
    text_id: "Peliharalah semua salat dan salat wustha, dan laksanakanlah (salat) karena Allah dengan khusyuk.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "When the sun reaches its zenith and distraction runs high, prayer serves as a cool shade and spiritual anchor.",
    explain_id: "Ketika matahari tegak di puncaknya dan kesibukan dunia mendidih, salat menjadi naungan sejuk penyegar iman.",
    quran_detail: { surah_no: 2, surah_name: "Al-Baqarah", surah_name_ar: "البقرة", ayah: 238, juz: 2 },
    hadith_detail: null,
    source_url: "https://quran.com/2/238",
    tags: ["prayer", "dhuhr", "focus", "obedience"]
  },
  {
    id: "2026-10-05-p4",
    date: "2026-10-05",
    slot: 4,
    phase_id: "p4_afternoon",
    phase_name_en: "Late Afternoon / Asr",
    phase_name_id: "Sore Hari / Ashar",
    time_range: "14:00-17:00",
    topic_en: "Patience and Fortitude",
    topic_id: "Kesabaran dan Keberkahan Sore",
    source_type: "hadith",
    arabic: "مَنْ تَرَكَ صَلَاةَ الْعَصْرِ فَقَدْ حَبِطَ عَمَلُهُ",
    text_en: "Whoever neglects the Asr prayer, his good deeds will be void.",
    text_id: "Barangsiapa meninggalkan salat Ashar, maka terhapuslah amal kebaikannya.",
    translation_credit: "Sahih al-Bukhari",
    explain_en: "A stark admonition against losing vigilance as the workday winds down; finishing strong with mindful presence.",
    explain_id: "Peringatan tegas agar tidak terlena saat hari menjelang sore; menutup hari dengan kesadaran penuh.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Times of the Prayers",
      hadith_no: 553,
      narrator: "Buraida (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Al-Bukhari"
    },
    source_url: "https://sunnah.com/bukhari:553",
    tags: ["asr", "vigilance", "finish-strong", "discipline"]
  },
  {
    id: "2026-10-05-p5",
    date: "2026-10-05",
    slot: 5,
    phase_id: "p5_sunset",
    phase_name_en: "Sunset / Maghrib",
    phase_name_id: "Senja / Maghrib",
    time_range: "17:00-19:00",
    topic_en: "Gratitude for the Horizon",
    topic_id: "Keindahan Langit Senja dan Keagungan-Nya",
    source_type: "quran",
    arabic: "فَلَا أُقْسِمُ بِالشَّفَقِ • وَاللَّيْلِ وَمَا وَسَقَ • وَالْقَمَرِ إِذَا اتَّسَقَ",
    text_en: "So I swear by the twilight glow, and by the night and what it envelopes, and by the moon when it becomes full.",
    text_id: "Maka Aku bersumpah demi cahaya merah di waktu senja, demi malam dan apa yang diselubunginya, dan demi bulan apabila telah purnama.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "The transition from gold to indigo invokes contemplation on the transient stages through which human life constantly travels.",
    explain_id: "Pergeseran warna langit senja mengajak manusia merenungi tahapan kehidupan yang terus bergulir menuju keabadian.",
    quran_detail: { surah_no: 84, surah_name: "Al-Inshiqaq", surah_name_ar: "الانشقاق", ayah: 16, juz: 30 },
    hadith_detail: null,
    source_url: "https://quran.com/84/16-18",
    tags: ["sunset", "twilight", "reflection", "nature"]
  },
  {
    id: "2026-10-05-p6",
    date: "2026-10-05",
    slot: 6,
    phase_id: "p6_evening",
    phase_name_en: "Early Night / Isha",
    phase_name_id: "Malam Awal / Isya",
    time_range: "19:00-22:00",
    topic_en: "Kindness & Restful Speech",
    topic_id: "Tutur Kata yang Lembut di Malam Hari",
    source_type: "quran",
    arabic: "وَقُولُوا لِلنَّاسِ حُسْنًا",
    text_en: "And speak to people good [words].",
    text_id: "Dan bertutur-katalah yang baik kepada manusia.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "As conversations close the day, soft, gracious speech heals the friction gathered in daytime interactions.",
    explain_id: "Saat hari berakhir, tutur kata yang hangat dan penuh kebaikan merajut kembali harmoni sesama manusia.",
    quran_detail: { surah_no: 2, surah_name: "Al-Baqarah", surah_name_ar: "البقرة", ayah: 83, juz: 1 },
    hadith_detail: null,
    source_url: "https://quran.com/2/83",
    tags: ["speech", "gentleness", "community", "evening"]
  },
  {
    id: "2026-10-05-p7",
    date: "2026-10-05",
    slot: 7,
    phase_id: "p7_midnight",
    phase_name_en: "Midnight / Deep Night",
    phase_name_id: "Tengah Malam",
    time_range: "22:00-02:00",
    topic_en: "Supplication Before Sleeping",
    topic_id: "Menyerahkan Jiwa Menjelang Tidur",
    source_type: "hadith",
    arabic: "بِاسْمِكَ رَبِّ وَضَعْتُ جَنْبِي وَبِكَ أَرْفَعُهُ إِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا بِمَا تَحْفَظُ بِهِ عِبَادَكَ الصَّالِحِينَ",
    text_en: "In Your name, my Lord, I lay down my side and in Your name I raise it. If You hold my soul, have mercy upon it, and if You release it, protect it as You protect Your righteous slaves.",
    text_id: "Dengan nama-Mu wahai Tuhanku, aku meletakkan lambungku dan dengan nama-Mu aku mengangkatnya. Jika Engkau menahan jiwaku maka kasihanilah, dan jika Engkau melepaskannya maka jagalah sebagaimana Engkau menjaga hamba-hamba-Mu yang saleh.",
    translation_credit: "Sahih al-Bukhari & Muslim",
    explain_en: "Sleep is the minor transition of consciousness; surrendering the soul to divine custody yields untroubled serenity.",
    explain_id: "Tidur adalah pasrah total; mempercayakan jiwa pada penjagaan Ilahi menghadirkan kedamaian tanpa rasa takut.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Book of Invocations",
      hadith_no: 6320,
      narrator: "Abu Hurairah (RA)",
      grading: "Sahih (Muttafaqun 'Alayh)",
      grading_by: "Al-Bukhari & Muslim"
    },
    source_url: "https://sunnah.com/bukhari:6320",
    tags: ["sleep", "surrender", "trust", "midnight"]
  },
  {
    id: "2026-10-05-p8",
    date: "2026-10-05",
    slot: 8,
    phase_id: "p8_predawn",
    phase_name_en: "Pre-Dawn / Tahajjud",
    phase_name_id: "Sepertiga Malam Terakhir",
    time_range: "02:00-05:00",
    topic_en: "The Divine Descent & Answered Prayers",
    topic_id: "Turunnya Rahmat di Sepertiga Malam",
    source_type: "hadith",
    arabic: "يَنْزِلُ رَبُّنَا تَبَارَكَ وَتَعَالَى كُلَّ لَيْلَةٍ إِلَى السَّمَاءِ الدُّنْيَا حِينَ يَبْقَى ثُلُثُ اللَّيْلِ الآخِرُ يَقُولُ مَنْ يَدْعُونِي فَأَسْتَجِيبَ لَهُ مَنْ يَسْأَلُنِي فَأُعْطِيَهُ مَنْ يَسْتَغْفِرُنِي فَأَغْفِرَ لَهُ",
    text_en: "Our Lord, Blessed and Exalted, descends each night to the lowest heaven when the last third of the night remains, saying: 'Who calls upon Me that I may answer him? Who asks of Me that I may give him? Who seeks My forgiveness that I may forgive him?'",
    text_id: "Tuhan kita Tabaraka wa Ta'ala turun setiap malam ke langit dunia pada sepertiga malam terakhir, seraya berfirman: 'Siapa yang berdoa kepada-Ku niscaya Aku kabulkan, siapa yang meminta kepada-Ku niscaya Aku beri, dan siapa yang memohon ampun kepada-Ku niscaya Aku ampuni.'",
    translation_credit: "Sahih al-Bukhari & Muslim",
    explain_en: "The most intimate station of human-divine communion, where sincerity is unadulterated by any spectators.",
    explain_id: "Puncak keintiman seorang hamba dengan Tuhannya, di mana doa dipanjatkan murni tanpa riya.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Book of Tahajjud (Night Prayer)",
      hadith_no: 1145,
      narrator: "Abu Hurairah (RA)",
      grading: "Sahih (Muttafaqun 'Alayh)",
      grading_by: "Al-Bukhari & Muslim"
    },
    source_url: "https://sunnah.com/bukhari:1145",
    tags: ["tahajjud", "dua", "forgiveness", "mercy"]
  },

  // ==========================================
  // DAY 3: 2026-10-06 (Tomorrow)
  // ==========================================
  {
    id: "2026-10-06-p1",
    date: "2026-10-06",
    slot: 1,
    phase_id: "p1_dawn",
    phase_name_en: "Dawn / Fajr",
    phase_name_id: "Pagi / Fajar",
    time_range: "05:00-08:00",
    topic_en: "The Weight of the Two Rak'ahs of Dawn",
    topic_id: "Dua Rakaat Sebelum Fajar",
    source_type: "hadith",
    arabic: "رَكْعَتَا الْفَجْرِ خَيْرٌ مِنَ الدُّنْيَا وَمَا فِيهَا",
    text_en: "The two rak'ahs before dawn are better than the entire world and everything within it.",
    text_id: "Dua rakaat (sebelum) subuh lebih baik daripada dunia beserta seluruh isinya.",
    translation_credit: "Sahih Muslim",
    explain_en: "A striking recalibration of value: the inner wealth of conscious prayer outweighs all material wealth.",
    explain_id: "Menimbang kembali hakikat nilai: ketenangan spiritual jauh melampaui seluruh perhiasan materi dunia.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "The Book of Prayer - Travellers",
      hadith_no: 725,
      narrator: "Aisha (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:725",
    tags: ["fajr", "sunnah", "wealth", "perspective"]
  },
  {
    id: "2026-10-06-p2",
    date: "2026-10-06",
    slot: 2,
    phase_id: "p2_morning",
    phase_name_en: "Mid-Morning",
    phase_name_id: "Dhuha / Pagi Menjelang Siang",
    time_range: "08:00-11:00",
    topic_en: "Trust in Divine Provision",
    topic_id: "Tawakal Seperti Burung di Pagi Hari",
    source_type: "hadith",
    arabic: "لَوْ أَنَّكُمْ تَوَكَّلُونَ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرَزَقَكُمْ كَمَا يَرْزُقُ الطَّيْرَ تَغْدُو خِمَاصًا وَتَرُوحُ بِطَانًا",
    text_en: "If you were to rely upon Allah with true reliance, He would provide for you just as He provides for the birds: they go out in the morning hungry and return full.",
    text_id: "Seandainya kalian bertawakal kepada Allah dengan sebenar-benar tawakal, niscaya Dia akan memberi rezeki sebagaimana burung: pergi di pagi hari dalam keadaan lapar dan pulang di sore hari dengan kenyang.",
    translation_credit: "Jami' at-Tirmidhi",
    explain_en: "True reliance is active, not passive. The bird leaves its nest at dawn to seek food, demonstrating faith joined with vigorous effort.",
    explain_id: "Tawakal sejati bukanlah berdiam diri. Burung mengepakkan sayap keluar sarang di pagi hari, memadukan iman dengan ikhtiar nyata.",
    quran_detail: null,
    hadith_detail: {
      collection: "Jami' at-Tirmidhi",
      book: "Chapters on Zuhd",
      hadith_no: 2344,
      narrator: "Umar ibn Al-Khattab (RA)",
      grading: "Hasan Sahih (Good & Authentic)",
      grading_by: "At-Tirmidhi"
    },
    source_url: "https://sunnah.com/tirmidhi:2344",
    tags: ["tawakkul", "provision", "effort", "morning"]
  },
  {
    id: "2026-10-06-p3",
    date: "2026-10-06",
    slot: 3,
    phase_id: "p3_noon",
    phase_name_en: "High Noon / Dhuhr",
    phase_name_id: "Siang Terik / Dzuhur",
    time_range: "11:00-14:00",
    topic_en: "Humility Amidst Power",
    topic_id: "Kerendahan Hati di Puncak Kejayaan",
    source_type: "quran",
    arabic: "وَلَا تَمْشِ فِي الْأَرْضِ مَرَحًا إِنَّكَ لَنْ تَخْرِقَ الْأَرْضَ وَلَنْ تَبْلُغَ الْجِبَالَ طُولًا",
    text_en: "And do not walk upon the earth exultantly. Indeed, you will never tear the earth [apart], and you will never reach the mountains in height.",
    text_id: "Dan janganlah engkau berjalan di bumi ini dengan sombong, karena sesungguhnya engkau tidak akan dapat menembus bumi dan tidak akan mencapai tinggi gunung.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Reminding human beings of their fragility precisely when accomplishments tempt arrogance during peak hours.",
    explain_id: "Mengingatkan kembali kerapuhan manusia justru di saat pencapaian duniawi menggoda lahirnya kesombongan.",
    quran_detail: { surah_no: 17, surah_name: "Al-Isra", surah_name_ar: "الإسراء", ayah: 37, juz: 15 },
    hadith_detail: null,
    source_url: "https://quran.com/17/37",
    tags: ["humility", "character", "perspective", "wisdom"]
  },
  {
    id: "2026-10-06-p4",
    date: "2026-10-06",
    slot: 4,
    phase_id: "p4_afternoon",
    phase_name_en: "Late Afternoon / Asr",
    phase_name_id: "Sore Hari / Ashar",
    time_range: "14:00-17:00",
    topic_en: "The Shadow and Divine Proportion",
    topic_id: "Bayangan Sore yang Merunduk",
    source_type: "quran",
    arabic: "أَلَمْ تَرَ إِلَىٰ رَبِّكَ كَيْفَ مَدَّ الظِّلَّ وَلَوْ شَاءَ لَجَعَلَهُ سَاكِنًا",
    text_en: "Have you not considered your Lord - how He extends the shadow? And if He willed, He could have made it stationary.",
    text_id: "Tidakkah engkau memperhatikan (penciptaan) Tuhanmu, bagaimana Dia memanjangkan bayang-bayang? Sekiranya Dia menghendaki, niscaya Dia menjadikannya tetap.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "The lengthening afternoon shadow is an astronomical witness to cosmic order, prompting meditative gratitude.",
    explain_id: "Memanjangnya bayang-bayang di waktu sore adalah bukti keteraturan kosmos yang mengundang kekaguman pada Sang Pencipta.",
    quran_detail: { surah_no: 25, surah_name: "Al-Furqan", surah_name_ar: "الفرقان", ayah: 45, juz: 19 },
    hadith_detail: null,
    source_url: "https://quran.com/25/45",
    tags: ["nature", "afternoon", "cosmology", "reflection"]
  },
  {
    id: "2026-10-06-p5",
    date: "2026-10-06",
    slot: 5,
    phase_id: "p5_sunset",
    phase_name_en: "Sunset / Maghrib",
    phase_name_id: "Senja / Maghrib",
    time_range: "17:00-19:00",
    topic_en: "Protection at Nightfall",
    topic_id: "Doa Perlindungan Menjelang Petang",
    source_type: "hadith",
    arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ وَالْحَمْدُ لِلَّهِ لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ",
    text_en: "We have reached the evening and the kingdom belongs to Allah, and all praise is for Allah; none has the right to be worshipped except Allah alone, without partner.",
    text_id: "Kami telah memasuki waktu petang dan kerajaan ini milik Allah, segala puji bagi Allah, tidak ada Tuhan selain Allah semata yang tiada sekutu bagi-Nya.",
    translation_credit: "Sahih Muslim",
    explain_en: "Pronouncing the evening invocation aligns one's awareness as day surrenders its light to the night sky.",
    explain_id: "Membaca dzikir petang menenangkan hati saat peralihan terang menjadi gelap.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih Muslim",
      book: "Book of Prayers & Remembrances",
      hadith_no: 2723,
      narrator: "Abdullah ibn Mas'ud (RA)",
      grading: "Sahih (Authentic)",
      grading_by: "Muslim"
    },
    source_url: "https://sunnah.com/muslim:2723",
    tags: ["sunset", "evening-adhkar", "surrender", "sovereignty"]
  },
  {
    id: "2026-10-06-p6",
    date: "2026-10-06",
    slot: 6,
    phase_id: "p6_evening",
    phase_name_en: "Early Night / Isha",
    phase_name_id: "Malam Awal / Isya",
    time_range: "19:00-22:00",
    topic_en: "Purity of Heart Towards All",
    topic_id: "Kebersihan Hati Sebelum Pejam",
    source_type: "hadith",
    arabic: "لاَ تَبَاغَضُوا وَلاَ تَحَاسَدُوا وَلاَ تَدَابَرُوا وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا",
    text_en: "Do not hate one another, do not envy one another, do not turn away from one another, but be, O servants of Allah, brothers.",
    text_id: "Janganlah kalian saling membenci, saling mendengki, dan saling membelakangi. Jadilah kalian hamba-hamba Allah yang bersaudara.",
    translation_credit: "Sahih al-Bukhari & Muslim",
    explain_en: "Releasing malice, grudge, and competitive friction before nightfall grants wholesome sleep and clean conscience.",
    explain_id: "Membuang rasa benci dan dengki sebelum terlelap menghasilkan tidur yang berkualitas dan hati yang lapang.",
    quran_detail: null,
    hadith_detail: {
      collection: "Sahih al-Bukhari",
      book: "Good Manners and Form (Al-Adab)",
      hadith_no: 6065,
      narrator: "Anas ibn Malik (RA)",
      grading: "Sahih (Muttafaqun 'Alayh)",
      grading_by: "Al-Bukhari & Muslim"
    },
    source_url: "https://sunnah.com/bukhari:6065",
    tags: ["brotherhood", "purity", "forgiveness", "night"]
  },
  {
    id: "2026-10-06-p7",
    date: "2026-10-06",
    slot: 7,
    phase_id: "p7_midnight",
    phase_name_en: "Midnight / Deep Night",
    phase_name_id: "Tengah Malam",
    time_range: "22:00-02:00",
    topic_en: "The Quiet Majesty of Heaven",
    topic_id: "Merenungi Bintang di Tengah Malam",
    source_type: "quran",
    arabic: "إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِأُولِي الْأَلْبَابِ",
    text_en: "Indeed, in the creation of the heavens and the earth and the alternation of the night and the day are signs for those of understanding.",
    text_id: "Sesungguhnya dalam penciptaan langit dan bumi, dan silih bergantinya malam dan siang terdapat tanda-tanda bagi orang-orang yang berakal.",
    translation_credit: "Sahih International / Kemenag RI",
    explain_en: "Midnight contemplation of celestial order expands perspective beyond fleeting temporal troubles.",
    explain_id: "Renungan tengah malam atas luasnya langit melonggarkan himpitan masalah duniawi yang fana.",
    quran_detail: { surah_no: 3, surah_name: "Ali 'Imran", surah_name_ar: "آل عمران", ayah: 190, juz: 4 },
    hadith_detail: null,
    source_url: "https://quran.com/3/190",
    tags: ["night", "intellect", "creation", "universe"]
  },
  {
    id: "2026-10-06-p8",
    date: "2026-10-06",
    slot: 8,
    phase_id: "p8_predawn",
    phase_name_en: "Pre-Dawn / Tahajjud",
    phase_name_id: "Sepertiga Malam Terakhir",
    time_range: "02:00-05:00",
    topic_en: "The Night Prayer as the Ornament of the Righteous",
    topic_id: "Salat Malam Lambang Kehormatan Mukmin",
    source_type: "hadith",
    arabic: "عَلَيْكُمْ بِقِيَامِ اللَّيْلِ فَإِنَّهُ دَأْبُ الصَّالِحِينَ قَبْلَكُمْ وَقُرْبَةٌ إِلَى اللَّهِ تَعَالَى وَمَنْهَاةٌ عَنِ الإِثْمِ",
    text_en: "Hold fast to the night prayer, for it was the habit of the righteous before you, a means of drawing close to Allah, and a shield against sin.",
    text_id: "Hendaklah kalian mendirikan salat malam, karena itu adalah kebiasaan orang-orang saleh sebelum kalian, sarana mendekatkan diri kepada Allah, dan penghapus dosa.",
    translation_credit: "Jami' at-Tirmidhi",
    explain_en: "Pre-dawn vigil builds internal fortitude and moral stamina that guards against spiritual decay throughout the coming day.",
    explain_id: "Salat malam membentuk ketahanan batin dan imunitas moral yang membentengi diri sepanjang hari berikutnya.",
    quran_detail: null,
    hadith_detail: {
      collection: "Jami' at-Tirmidhi",
      book: "Chapters on Invocations",
      hadith_no: 3549,
      narrator: "Abu Umamah (RA)",
      grading: "Hasan (Good)",
      grading_by: "Al-Albani / At-Tirmidhi"
    },
    source_url: "https://sunnah.com/tirmidhi:3549",
    tags: ["tahajjud", "vigil", "character", "predawn"]
  }
];

// Phase metadata dictionary with 5 Fardhu Prayer & Sunnah times
window.PHASES_CONFIG = [
  { id: "p1_dawn", slot: 1, name_en: "Dawn / Fajr", name_id: "Pagi / Fajar", range: "05:00-08:00", startHour: 5, endHour: 8, color: "hsl(42, 92%, 55%)", icon: "🌅", prayer_name: "Shalat Subuh", prayer_type: "fardhu", rakaat: 2, tasyahhud: 1 },
  { id: "p2_morning", slot: 2, name_en: "Mid-Morning", name_id: "Dhuha / Menjelang Siang", range: "08:00-11:00", startHour: 8, endHour: 11, color: "hsl(48, 96%, 53%)", icon: "☀️", prayer_name: "Shalat Dhuha", prayer_type: "sunnah", rakaat: "2–8", tasyahhud: 1 },
  { id: "p3_noon", slot: 3, name_en: "High Noon / Dhuhr", name_id: "Siang Terik / Dzuhur", range: "11:00-14:00", startHour: 11, endHour: 14, color: "hsl(198, 88%, 48%)", icon: "🌞", prayer_name: "Shalat Dzuhur", prayer_type: "fardhu", rakaat: 4, tasyahhud: 2 },
  { id: "p4_afternoon", slot: 4, name_en: "Late Afternoon / Asr", name_id: "Sore Hari / Ashar", range: "14:00-17:00", startHour: 14, endHour: 17, color: "hsl(24, 85%, 52%)", icon: "🌤️", prayer_name: "Shalat Ashar", prayer_type: "fardhu", rakaat: 4, tasyahhud: 2 },
  { id: "p5_sunset", slot: 5, name_en: "Sunset / Maghrib", name_id: "Senja / Maghrib", range: "17:00-19:00", startHour: 17, endHour: 19, color: "hsl(340, 75%, 56%)", icon: "🌇", prayer_name: "Shalat Maghrib", prayer_type: "fardhu", rakaat: 3, tasyahhud: 2 },
  { id: "p6_evening", slot: 6, name_en: "Early Night / Isha", name_id: "Malam Awal / Isya", range: "19:00-22:00", startHour: 19, endHour: 22, color: "hsl(228, 62%, 54%)", icon: "🌌", prayer_name: "Shalat Isya", prayer_type: "fardhu", rakaat: 4, tasyahhud: 2 },
  { id: "p7_midnight", slot: 7, name_en: "Midnight / Deep Night", name_id: "Tengah Malam", range: "22:00-02:00", startHour: 22, endHour: 2, color: "hsl(265, 50%, 48%)", icon: "🌙", prayer_name: "Shalat Witir", prayer_type: "sunnah", rakaat: "1–3", tasyahhud: 1 },
  { id: "p8_predawn", slot: 8, name_en: "Pre-Dawn / Tahajjud", name_id: "Sepertiga Malam Terakhir", range: "02:00-05:00", startHour: 2, endHour: 5, color: "hsl(182, 70%, 46%)", icon: "✨", prayer_name: "Shalat Tahajjud", prayer_type: "sunnah", rakaat: "2–11", tasyahhud: 1 }
];

// ============================================================================
// PRAYER FIQH GUIDE (TATA CARA & PANDUAN LENGKAP 5 WAKTU FARDHU & SUNNAH)
// ============================================================================
window.PRAYER_FIQH_DATA = {
  1: {
    slot: 1,
    name: "Shalat Subuh",
    status: "Fardhu 'Ain (Wajib)",
    rakaat: "2 Rakaat",
    tasyahhud: "1 Kali (Tasyahhud Akhir pada rakaat kedua)",
    bacaan_jahr: "Ya (Ayat dibaca lantang/nyaring pada rakaat 1 & 2)",
    waktu_masuk: "Terbit fajar shadiq hingga sesaat sebelum terbit piringan matahari (Syuruq).",
    keutamaan: "Dua rakaat fajar lebih baik dari dunia dan seisinya (HR. Muslim 725). Shalat Subuh berjamaah mendapat jaminan perlindungan Allah sepanjang hari.",
    how_to_pray: [
      "1. Niat ikhlas karena Allah & Takbiratul Ihram ('Allāhu Akbar').",
      "2. Berdiri membaca Doa Iftitah, Surah Al-Fatihah (Wajib), dan surah Al-Qur'an pilihan secara lantang (jahr).",
      "3. Ruku' dengan thuma'ninah (Tasbih: Subhāna Rabbiyal 'Azhīmi wa bihamdih 3x).",
      "4. I'tidal dengan thuma'ninah (Sami'allāhu liman hamidah... Rabbanā lakal hamd...). Mazhab Syafi'i mensunnahkan Doa Qunut Subuh pada i'tidal rakaat ke-2.",
      "5. Sujud dua kali dengan thuma'ninah (Subhāna Rabbiyal A'lā wa bihamdih 3x) diselingi duduk antara dua sujud.",
      "6. Bangkit untuk rakaat kedua, ulangi membaca Al-Fatihah, surah, ruku', i'tidal, dan sujud.",
      "7. Duduk Tasyahhud Akhir membaca Tasyahhud dan Shalawat Ibrahimiyah.",
      "8. Mengucapkan Salam ke kanan dan ke kiri."
    ],
    dzikir_after: "Istighfar 3x, Allāhumma antas salām..., membaca Ayat Kursi, Al-Ikhlas, Al-Falaq, An-Nas, Tasbih, Tahmid, Takbir 33x."
  },
  2: {
    slot: 2,
    name: "Shalat Dhuha",
    status: "Sunnah Mu'akkadah",
    rakaat: "2 hingga 8 Rakaat (Tiap 2 rakaat satu salam)",
    tasyahhud: "1 Kali tiap 2 rakaat",
    bacaan_jahr: "Tidak (Dibaca pelan / sirr)",
    waktu_masuk: "Matahari naik setinggi satu tombak (sekitar 15-20 menit setelah Syuruq) hingga menjelang waktu Dzuhur (Zawal).",
    keutamaan: "Menggugurkan kewajiban sedekah atas 360 persendian tubuh setiap hari (HR. Muslim 720) dan mengundang keberkahan rezeki.",
    how_to_pray: [
      "1. Niat shalat sunnah Dhuha dua rakaat karena Allah & Takbiratul Ihram.",
      "2. Membaca Al-Fatihah dan surah pendek (misal: Asy-Syams / Ad-Dhuha) secara lirih (sirr).",
      "3. Ruku', I'tidal, dan Sujud dua kali dengan thuma'ninah.",
      "4. Bangkit untuk rakaat kedua, ulangi rukun lalu duduk Tasyahhud Akhir.",
      "5. Salam. Jika menambah rakaat, ulangi rangkaian dua rakaat salam berikutnya."
    ],
    dzikir_after: "Membaca doa Dhuha: Allāhumma innad dhuhā'a dhuhā'uk, wal bahā'a bahā'uk, wal quwwata quwwatuk..."
  },
  3: {
    slot: 3,
    name: "Shalat Dzuhur",
    status: "Fardhu 'Ain (Wajib)",
    rakaat: "4 Rakaat",
    tasyahhud: "2 Kali (Tasyahhud Awal di rakaat ke-2 & Tasyahhud Akhir di rakaat ke-4)",
    bacaan_jahr: "Tidak (Dibaca sirr/lirih pada seluruh 4 rakaat)",
    waktu_masuk: "Tergelincirnya matahari ke arah barat (Zawal) hingga panjang bayangan sama dengan panjang benda aslinya.",
    keutamaan: "Waktu dibukanya pintu-pintu langit di mana amal saleh diangkat ke hadapan Allah (HR. Tirmidzi 478).",
    how_to_pray: [
      "1. Niat shalat fardhu Dzuhur 4 rakaat & Takbiratul Ihram.",
      "2. Rakaat 1 & 2: Membaca Iftitah, Al-Fatihah, dan surah pilihan secara lirih (sirr), lalu ruku', i'tidal, dan sujud dua kali.",
      "3. Setelah sujud kedua di rakaat ke-2, duduk Tasyahhud Awal (membaca Attahiyyatul Mubarakatus...).",
      "4. Bangkit berdiri untuk rakaat ke-3 dan ke-4: Hanya membaca Surah Al-Fatihah (tanpa surah tambahan).",
      "5. Ruku', i'tidal, sujud dua kali pada rakaat ke-4, lalu duduk Tasyahhud Akhir membaca Tasyahhud dan Shalawat Ibrahimiyah.",
      "6. Mengucapkan Salam ke kanan dan ke kiri."
    ],
    dzikir_after: "Istighfar 3x, zikir tauhid, tasbih 33x, tahmid 33x, takbir 33x, diakhiri laa ilaaha illallaah..."
  },
  4: {
    slot: 4,
    name: "Shalat Ashar (Ash-Shalatul Wustha)",
    status: "Fardhu 'Ain (Wajib Mu'akkad)",
    rakaat: "4 Rakaat",
    tasyahhud: "2 Kali (Tasyahhud Awal di rakaat ke-2 & Tasyahhud Akhir di rakaat ke-4)",
    bacaan_jahr: "Tidak (Dibaca sirr/lirih)",
    waktu_masuk: "Panjang bayangan melebihi panjang benda aslinya hingga menjelang matahari terbenam (sangat makruh menunda sampai matahari menguning).",
    keutamaan: "Shalat yang dijuluki Shalat Wustha dalam Al-Qur'an (QS. Al-Baqarah: 238). Siapa meninggalkannya, amalnya gugur (HR. Bukhari 553).",
    how_to_pray: [
      "1. Niat shalat fardhu Ashar 4 rakaat & Takbiratul Ihram.",
      "2. Pelaksanaan sama persis dengan Shalat Dzuhur (4 rakaat sirr dengan dua tasyahhud).",
      "3. Disunnahkan menjaga konsentrasi tinggi karena waktu pergantian malaikat siang dan malam.",
      "4. Duduk Tasyahhud Akhir dan mengucapkan Salam."
    ],
    dzikir_after: "Dzikir bakda shalat fardhu dan dilanjutkan dengan Dzikir Petang (Al-Ma'tsurat / doa perlindungan malam)."
  },
  5: {
    slot: 5,
    name: "Shalat Maghrib",
    status: "Fardhu 'Ain (Wajib)",
    rakaat: "3 Rakaat",
    tasyahhud: "2 Kali (Tasyahhud Awal di rakaat ke-2 & Tasyahhud Akhir di rakaat ke-3)",
    bacaan_jahr: "Ya (Jahr/lantang pada rakaat 1 & 2, sirr/lirih pada rakaat ke-3)",
    waktu_masuk: "Terbenamnya piringan matahari sempurna hingga hilangnya mega merah (syafaqul ahmar) di ufuk barat.",
    keutamaan: "Waktu mustajab pergantian hari hijriyah baru; menyambut datangnya malam dengan penghambaan yang khusyuk.",
    how_to_pray: [
      "1. Niat shalat fardhu Maghrib 3 rakaat & Takbiratul Ihram.",
      "2. Rakaat 1 & 2: Membaca Al-Fatihah dan surah pendek secara jahr (nyaring), lalu ruku', i'tidal, sujud dua kali.",
      "3. Setelah sujud kedua di rakaat ke-2, duduk Tasyahhud Awal.",
      "4. Bangkit untuk rakaat ke-3: Hanya membaca Al-Fatihah secara sirr (lirih), ruku', i'tidal, sujud dua kali.",
      "5. Duduk Tasyahhud Akhir membaca shalawat lengkap, lalu Salam."
    ],
    dzikir_after: "Istighfar, zikir bakda shalat, disunnahkan melaksanakan 2 rakaat Ba'diyah Maghrib."
  },
  6: {
    slot: 6,
    name: "Shalat Isya",
    status: "Fardhu 'Ain (Wajib)",
    rakaat: "4 Rakaat",
    tasyahhud: "2 Kali (Tasyahhud Awal di rakaat ke-2 & Tasyahhud Akhir di rakaat ke-4)",
    bacaan_jahr: "Ya (Jahr/lantang pada rakaat 1 & 2, sirr pada rakaat 3 & 4)",
    waktu_masuk: "Hilangnya mega merah hingga sepertiga malam pertama (batas darurat: terbit fajar Subuh).",
    keutamaan: "Shalat Isya berjamaah diganjar pahala laksana shalat setengah malam suntuk (HR. Muslim 656).",
    how_to_pray: [
      "1. Niat shalat fardhu Isya 4 rakaat & Takbiratul Ihram.",
      "2. Rakaat 1 & 2: Membaca Al-Fatihah dan surah secara nyaring (jahr), ruku', i'tidal, sujud.",
      "3. Duduk Tasyahhud Awal pada rakaat ke-2.",
      "4. Rakaat 3 & 4: Hanya membaca Al-Fatihah secara lirih (sirr), ruku', i'tidal, sujud.",
      "5. Duduk Tasyahhud Akhir dan mengucapkan Salam."
    ],
    dzikir_after: "Dzikir bakda shalat, disunnahkan Shalat Ba'diyah Isya 2 rakaat."
  },
  7: {
    slot: 7,
    name: "Shalat Witir",
    status: "Sunnah Mu'akkadah",
    rakaat: "1 hingga 3 Rakaat (Ganjil)",
    tasyahhud: "Bisa 2 rakaat salam + 1 rakaat salam, atau 3 rakaat langsung 1 tasyahhud",
    bacaan_jahr: "Boleh jahr jika dilakukan di malam hari",
    waktu_masuk: "Setelah shalat Isya hingga menjelang fajar Subuh (penutup shalat malam).",
    keutamaan: "'Jadikanlah akhir shalat kalian di malam hari adalah shalat witir' (HR. Bukhari 998).",
    how_to_pray: [
      "1. Jika 3 rakaat: Shalat 2 rakaat salam (Al-A'la & Al-Kafirun), lalu berdiri shalat 1 rakaat witir (Al-Ikhlas, Al-Falaq, An-Nas).",
      "2. Pada separuh akhir Ramadhan, disunnahkan membaca Doa Qunut Witir pada i'tidal rakaat terakhir.",
      "3. Duduk Tasyahhud Akhir dan Salam."
    ],
    dzikir_after: "Membaca: Subhāna Malikil Quddūs (3x, dipanjangkan pada ketiga), Rabbil malā'ikati war rūh."
  },
  8: {
    slot: 8,
    name: "Shalat Tahajjud (Qiyamul Lail)",
    status: "Sunnah Mu'akkadah (Sangat Dianjurkan)",
    rakaat: "Minimal 2 Rakaat (Optimal 8 hingga 11 rakaat bersama Witir)",
    tasyahhud: "Tiap 2 rakaat satu salam",
    bacaan_jahr: "Boleh jahr sedang / lirih khusyuk",
    waktu_masuk: "Sepertiga malam terakhir (sekitar pukul 02:00 - 04:30) setelah bangun dari tidur.",
    keutamaan: "Mendapat kedudukan terpuji (Maqaman Mahmuda, QS. Al-Isra: 79). Waktu mustajab saat Allah turun ke langit dunia mengijabah doa (HR. Bukhari 1145).",
    how_to_pray: [
      "1. Bangun tidur, bersiwak, berwudhu, membaca 10 ayat terakhir Surah Ali 'Imran.",
      "2. Memulai dengan 2 rakaat ringan (Shalat Iftitah).",
      "3. Melanjutkan shalat 2 rakaat demi 2 rakaat dengan bacaan panjang, ruku' dan sujud yang khusyuk.",
      "4. Memperbanyak istighfar (Sayyidul Istighfar) di waktu Sahur menjelang Subuh.",
      "5. Ditutup dengan shalat Witir jika belum witir di awal malam."
    ],
    dzikir_after: "Istighfar sebanyak-banyaknya di waktu Sahur (wabil ash-hāri hum yastaghfirūn)."
  }
};

// ============================================================================
// EVENT TIMELINE DATASET: KRONOLOGI AKHIRAT & TANDA KIAMAT
// Structured Chronology: Minor Signs (A-Z) -> 10 Major Signs -> Judgment Day
// Equipped with What Happens, Citations, and "How to Prepare with It"
// ============================================================================
window.EVENT_TIMELINE_DATA = [
  // --------------------------------------------------------------------------
  // STAGE 1: TANDA-TANDA KIAMAT SHUGHRA (MINOR SIGNS — NESTED A-Z)
  // --------------------------------------------------------------------------
  {
    id: "evt_minor_a",
    stage_id: "s1_minor",
    stage_num: 1,
    stage_title: "1. Tanda Kiamat Shughra (Kecil) — Katalog A-Z",
    event_code: "A",
    event_name: "A. Diutus & Wafatnya Rasulullah ﷺ",
    source_type: "hadith",
    reference: "HR. Al-Bukhari No. 6504 & Muslim No. 2951",
    grading: "Sahih (Muttafaqun 'Alayh)",
    arabic: "بُعِثْتُ أَنَا وَالسَّاعَةُ كَهَاتَيْنِ ، وَأَشَارَ بِإِصْبَعَيْهِ السَّبَّابَةِ وَالْوُسْطَى",
    translation: "Aku diutus bersamaan dengan hari Kiamat laksana dua jari ini (beliau berisyarat dengan jari telunjuk dan jari tengahnya).",
    what_happens: "Rasulullah ﷺ adalah Nabi akhir zaman dan penutup para Nabi. Sejak diutusnya beliau, waktu bergulirnya alam semesta telah memasuki fase paling akhir dalam sejarah umat manusia.",
    preparation_guide: "Berpegang teguh pada Sunnah Nabi ﷺ dan Al-Qur'an, meneladani akhlak beliau, serta memperbanyak shalawat agar mendapat syafa'at di hari kiamat.",
    source_url: "https://sunnah.com/bukhari:6504",
    tags: ["minor_sign", "prophet", "beginning"]
  },
  {
    id: "evt_minor_b",
    stage_id: "s1_minor",
    stage_num: 1,
    stage_title: "1. Tanda Kiamat Shughra (Kecil) — Katalog A-Z",
    event_code: "B",
    event_name: "B. Hilangnya Amanah & Jabatan Diberikan Bukan Ahlinya",
    source_type: "hadith",
    reference: "HR. Al-Bukhari No. 6496",
    grading: "Sahih",
    arabic: "إِذَا ضُيِّعَتِ الأَمَانَةُ فَانْتَظِرِ السَّاعَةَ ... إِذَا وُسِّدَ الأَمْرُ إِلَى غَيْرِ أَهْلِهِ فَانْتَظِرِ السَّاعَةَ",
    translation: "Jika amanah telah disia-siakan, maka tunggulah hari Kiamat... Jika urusan diserahkan kepada yang bukan ahlinya, maka tunggulah hari Kiamat.",
    what_happens: "Integritas moral merosot drastis. Kepemimpinan, kehakiman, dan fatwa agama dipegang oleh orang-orang yang mengejar kepentingan pribadi tanpa ilmu dan takwa.",
    preparation_guide: "Menjaga amanah sekecil apa pun dalam pekerjaan dan keluarga, tidak rakus meminta jabatan publik, serta menuntut ilmu syar'i agar tidak tersesat oleh pemimpin bodoh.",
    source_url: "https://sunnah.com/bukhari:6496",
    tags: ["minor_sign", "trust", "leadership"]
  },
  {
    id: "evt_minor_c",
    stage_id: "s1_minor",
    stage_num: 1,
    stage_title: "1. Tanda Kiamat Shughra (Kecil) — Katalog A-Z",
    event_code: "C",
    event_name: "C. Perlombaan Membangun Gedung Tinggi",
    source_type: "hadith",
    reference: "HR. Muslim No. 8 (Hadits Jibril)",
    grading: "Sahih",
    arabic: "وَأَنْ تَرَى الْحُفَاةَ الْعُرَاةَ الْعَالَةَ رِعَاءَ الشَّاءِ يَتَطَاوَلُونَ فِي الْبُنْيَانِ",
    translation: "Dan engkau menyaksikan orang-orang yang tidak beralas kaki, telanjang, miskin, dan penggembala domba saling berlomba-lomba meninggikan gedung-gedung.",
    what_happens: "Masyarakat yang dahulunya miskin dan sederhana tiba-tiba berlimpah harta duniawi lalu saling berbangga-bangga membangun menara dan pencakar langit megah.",
    preparation_guide: "Zuhud terhadap kemewahan materi, tidak membangga-banggakan harta, dan menginvestasikan kelebihan rezeki untuk sedekah jariyah dan bekal akhirat.",
    source_url: "https://sunnah.com/muslim:8",
    tags: ["minor_sign", "buildings", "materialism"]
  },
  {
    id: "evt_minor_d",
    stage_id: "s1_minor",
    stage_num: 1,
    stage_title: "1. Tanda Kiamat Shughra (Kecil) — Katalog A-Z",
    event_code: "D",
    event_name: "D. Waktu Terasa Sangat Singkat & Cepat",
    source_type: "hadith",
    reference: "HR. At-Tirmidzi No. 2332",
    grading: "Sahih",
    arabic: "لاَ تَقُومُ السَّاعَةُ حَتَّى يَتَقَارَبَ الزَّمَانُ فَتَكُونَ السَّنَةُ كَالشَّهْرِ وَالشَّهْرُ كَالْجُمُعَةِ",
    translation: "Kiamat tidak akan terjadi sampai waktu terasa saling berdekatan (singkat), sehingga satu tahun terasa bagai sebulan, sebulan bagai sepekan, dan sepekan bagai sehari.",
    what_happens: "Hilangnya keberkahan waktu. Hari-hari berlalu begitu cepat tanpa disadari, sementara manusia lalai dari mengumpulkan amal kebajikan.",
    preparation_guide: "Disiplin manajemen waktu, menjaga shalat tepat waktu sebagai jangkar harian, dan menghindari kesia-siaan (distraksi media sosial yang membuang umur).",
    source_url: "https://sunnah.com/tirmidhi:2332",
    tags: ["minor_sign", "time", "urgency"]
  },
  {
    id: "evt_minor_e",
    stage_id: "s1_minor",
    stage_num: 1,
    stage_title: "1. Tanda Kiamat Shughra (Kecil) — Katalog A-Z",
    event_code: "E",
    event_name: "E. Maraknya Pembunuhan Tanpa Alasan Jelas (Al-Harj)",
    source_type: "hadith",
    reference: "HR. Muslim No. 157",
    grading: "Sahih",
    arabic: "وَالَّذِي نَفْسِي بِيَدِهِ لاَ تَذْهَبُ الدُّنْيَا حَتَّى يَأْتِيَ عَلَى النَّاسِ يَوْمٌ لاَ يَدْرِي الْقَاتِلُ فِيمَ قَتَلَ وَلاَ الْمَقْتُولُ فِيمَ قُتِلَ",
    translation: "Demi Dzat yang jiwaku berada di tangan-Nya, dunia tidak akan lenyap hingga datang suatu masa di mana pembunuh tidak tahu mengapa ia membunuh, dan yang dibunuh tidak tahu mengapa ia dibunuh.",
    what_happens: "Kekacauan sosial parah dan darah manusia menjadi sangat murah, kekerasan terjadi semata-mata karena dorongan fitnah dan kebencian.",
    preparation_guide: "Menahan tangan dan lisan dari menumpahkan darah atau menyebarkan kebencian, menjauhi lingkaran fitnah (uzlah jika diperlukan), dan menjaga keselamatan keluarga.",
    source_url: "https://sunnah.com/muslim:157",
    tags: ["minor_sign", "violence", "peace"]
  },
  {
    id: "evt_minor_f",
    stage_id: "s1_minor",
    stage_num: 1,
    stage_title: "1. Tanda Kiamat Shughra (Kecil) — Katalog A-Z",
    event_code: "F",
    event_name: "F. Jazirah Arab Menghijau Penuh Sungai",
    source_type: "hadith",
    reference: "HR. Muslim No. 157",
    grading: "Sahih",
    arabic: "لاَ تَقُومُ السَّاعَةُ حَتَّى تَعُودَ أَرْضُ الْعَرَبِ مُرُوجًا وَأَنْهَارًا",
    translation: "Kiamat tidak akan terjadi sampai tanah Arab kembali menjadi padang rumput yang hijau dan dialiri sungai-sungai.",
    what_happens: "Gurun tandus di semenanjung Arab berubah iklimnya menjadi subur, bervegetasi hijau, dan dipenuhi aliran air alami.",
    preparation_guide: "Menyadari kebenaran mukjizat sabda Nabi ﷺ, memperbaharui taubat, dan tidak terlena dengan perubahan alam duniawi.",
    source_url: "https://sunnah.com/muslim:157",
    tags: ["minor_sign", "arabia", "nature"]
  },

  // --------------------------------------------------------------------------
  // STAGE 2: TANDA-TANDA KIAMAT KUBRA (10 TANDA BESAR BERURUTAN)
  // --------------------------------------------------------------------------
  {
    id: "evt_major_1",
    stage_id: "s2_major",
    stage_num: 2,
    stage_title: "2. Tanda Kiamat Kubra (Besar) — 10 Tanda Dahsyat",
    event_code: "1",
    event_name: "1. Ad-Dukhan (Kabut Asap Tebal 40 Hari)",
    source_type: "quran",
    reference: "QS. Ad-Dukhan: 10-11",
    grading: "Kalamullah (Al-Qur'an Al-Karim)",
    arabic: "فَارْتَقِبْ يَوْمَ تَأْتِي السَّمَاءُ بِدُخَانٍ مُّبِينٍ • يَغْشَى النَّاسَ ۖ هَٰذَا عَذَابٌ أَلِيمٌ",
    translation: "Maka tunggulah hari ketika langit membawa kabut yang tampak jelas, yang meliputi manusia. Inilah azab yang pedih.",
    what_happens: "Kabut asap pekat menyelimuti seantero bumi selama 40 hari. Bagi orang beriman asap ini hanya menimbulkan efek seperti flu ringan, namun bagi orang kafir asap ini membuat tubuh mereka kepanasan dan menderita.",
    preparation_guide: "Membiasakan dzikir perlindungan, memperkuat keimanan batin agar tidak goncang saat teknologi dan cahaya matahari terhalang kabut tebal.",
    source_url: "https://quran.com/44/10",
    tags: ["major_sign", "dukhan", "smoke"]
  },
  {
    id: "evt_major_2",
    stage_id: "s2_major",
    stage_num: 2,
    stage_title: "2. Tanda Kiamat Kubra (Besar) — 10 Tanda Dahsyat",
    event_code: "2",
    event_name: "2. Munculnya Al-Masih Ad-Dajjal",
    source_type: "hadith",
    reference: "HR. Muslim No. 2937",
    grading: "Sahih",
    arabic: "مَا بَيْنَ خَلْقِ آدَمَ إِلَى قِيَامِ السَّاعَةِ خَلْقٌ أَكْبَرُ مِنَ الدَّجَّالِ",
    translation: "Tidak ada fitnah sejak penciptaan Adam hingga hari Kiamat yang lebih besar daripada fitnah Dajjal.",
    what_happens: "Sosok pendusta terbesar keluar membawa tipuan dahsyat: menghidupkan ilusi surga dan neraka, menurunkan hujan, dan menjelajahi seluruh pelosok bumi dalam 40 hari kecuali Mekkah dan Madinah.",
    preparation_guide: "1. Menghafal 10 ayat pertama Surah Al-Kahfi. 2. Membaca doa perlindungan fitnah Dajjal di setiap tasyahhud akhir sebelum salam (Allāhumma innī a'ūdzu bika min 'adzābi jahannam... wa min fitnatil masīhid dajjāl).",
    source_url: "https://sunnah.com/muslim:2937",
    tags: ["major_sign", "dajjal", "protection"]
  },
  {
    id: "evt_major_3",
    stage_id: "s2_major",
    stage_num: 2,
    stage_title: "2. Tanda Kiamat Kubra (Besar) — 10 Tanda Dahsyat",
    event_code: "3",
    event_name: "3. Turunnya Nabi Isa AS Putra Maryam",
    source_type: "hadith",
    reference: "HR. Muslim No. 2937 & Al-Bukhari No. 2222",
    grading: "Sahih (Muttafaqun 'Alayh)",
    arabic: "فَيَنْزِلُ عِنْدَ الْمَنَارَةِ الْبَيْضَاءِ شَرْقِيَّ دِمَشْقَ ... فَيَطْلُبُهُ حَتَّى يُدْرِكَهُ بِبَابِ لُدٍّ فَيَقْتُلُهُ",
    translation: "Nabi Isa AS turun di menara putih sebelah timur Damaskus... lalu mencari Dajjal hingga menemukannya di pintu Ludd (Palestina) dan membunuhnya.",
    what_happens: "Nabi Isa AS turun memimpin dengan syariat Nabi Muhammad ﷺ, membunuh Dajjal, mematahkan salib, menghapus jizyah, dan menciptakan era kedamaian dan keadilan sempurna di bumi.",
    preparation_guide: "Memperkuat akidah tauhid yang murni, mencintai seluruh Nabi Allah, dan senantiasa berada di barisan orang-orang beriman.",
    source_url: "https://sunnah.com/muslim:2937",
    tags: ["major_sign", "isa", "victory"]
  },
  {
    id: "evt_major_4",
    stage_id: "s2_major",
    stage_num: 2,
    stage_title: "2. Tanda Kiamat Kubra (Besar) — 10 Tanda Dahsyat",
    event_code: "4",
    event_name: "4. Keluarnya Ya'juj dan Ma'juj",
    source_type: "quran",
    reference: "QS. Al-Anbiya: 96-97",
    grading: "Kalamullah (Al-Qur'an Al-Karim)",
    arabic: "حَتَّىٰ إِذَا فُتِحَتْ يَأْجُوجُ وَمَأْجُوجُ وَهُم مِّن كُلِّ حَدَبٍ يَنسِلُونَ • وَاقْتَرَبَ الْوَعْدُ الْحَقُّ",
    translation: "Hingga apabila (tembok) Ya'juj dan Ma'juj dibuka, dan mereka turun dengan cepat dari seluruh bukit. Dan telah dekatlah janji yang benar (Kiamat).",
    what_happens: "Kaum perusak berjumlah luar biasa besar menjebol dinding pembatas, meminum habis air danau Thabariyah, hingga Allah membinasakan mereka melalui ulat di leher atas doa Nabi Isa AS.",
    preparation_guide: "Berlindung kepada Allah dari kehancuran massal, menjaga tawakal teguh saat menghadapi fitnah yang tak dapat dilawan dengan kekuatan fisik.",
    source_url: "https://quran.com/21/96",
    tags: ["major_sign", "yajuj_majuj", "destruction"]
  },
  {
    id: "evt_major_5",
    stage_id: "s2_major",
    stage_num: 2,
    stage_title: "2. Tanda Kiamat Kubra (Besar) — 10 Tanda Dahsyat",
    event_code: "5",
    event_name: "5. Terbitnya Matahari dari Barat (Taubat Ditutup)",
    source_type: "quran",
    reference: "QS. Al-An'am: 158 & HR. Bukhari 4635",
    grading: "Kalamullah / Sahih",
    arabic: "يَوْمَ يَأْتِي بَعْضُ آيَاتِ رَبِّكَ لَا يَنفَعُ نَفْسًا إِيمَانُهَا لَمْ تَكُنْ آمَنَتْ مِن قَبْلُ أَوْ كَسَبَتْ فِي إِيمَانِهَا خَيْرًا",
    translation: "Pada hari datangnya sebagian tanda kekuasaan Tuhanmu, tidak berguna lagi iman seseorang yang belum beriman sebelum itu atau belum berbuat kebajikan dalam masa imannya.",
    what_happens: "Hukum alam berbalik. Matahari terbit dari arah tenggelamnya. Pada saat itu, pintu taubat dikunci rapat oleh Allah untuk selamanya.",
    preparation_guide: "BERSEGERA TAUBAT NASHUHA SEKARANG JUGA! Jangan menunda taubat dan amal saleh karena jika matahari terbit dari barat, penyesalan tak berguna lagi.",
    source_url: "https://quran.com/6/158",
    tags: ["major_sign", "sunrise_west", "repentance"]
  },
  {
    id: "evt_major_6",
    stage_id: "s2_major",
    stage_num: 2,
    stage_title: "2. Tanda Kiamat Kubra (Besar) — 10 Tanda Dahsyat",
    event_code: "6",
    event_name: "6. Keluarnya Dabbatul Ardh (Binatang Melata)",
    source_type: "quran",
    reference: "QS. An-Naml: 82",
    grading: "Kalamullah (Al-Qur'an Al-Karim)",
    arabic: "وَإِذَا وَقَعَ الْقَوْلُ عَلَيْهِمْ أَخْرَجْنَا لَهُمْ دَابَّةً مِّنَ الْأَرْضِ تُكَلِّمُهُمْ أَنَّ النَّاسَ كَانُوا بِآيَاتِنَا لَا يُوقِنُونَ",
    translation: "Dan apabila perkataan (ketetapan azab) telah jatuh atas mereka, Kami keluarkan bagi mereka binatang melata dari bumi yang akan berbicara kepada mereka bahwa sesungguhnya manusia dahulu tidak yakin pada ayat-ayat Kami.",
    what_happens: "Muncul binatang ajaib dari tanah yang membawa tongkat Nabi Musa AS dan cincin Nabi Sulaiman AS, menandai wajah orang beriman menjadi bercahaya dan wajah orang kafir menjadi hitam legam.",
    preparation_guide: "Memurnikan hati dari nifaq (kemunafikan), menjaga keikhlasan amal agar terstempel sebagai golongan mukmin yang bercahaya.",
    source_url: "https://quran.com/27/82",
    tags: ["major_sign", "dabbah", "identity"]
  },

  // --------------------------------------------------------------------------
  // STAGE 3: TIUPAN SANGKAKALA (AS-SHUR)
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_shur",
    stage_id: "s3_shur",
    stage_num: 3,
    stage_title: "3. Tiupan Sangkakala (As-Shur)",
    event_code: "SANGKAKALA",
    event_name: "Tiupan Kematian (Sha'iq) & Tiupan Kebangkitan (Ba'ats)",
    source_type: "quran",
    reference: "QS. Az-Zumar: 68",
    grading: "Kalamullah (Al-Qur'an Al-Karim)",
    arabic: "وَنُفِخَ فِي الصُّورِ فَصَعِقَ مَن فِي السَّمَاوَاتِ وَمَن فِي الْأَرْضِ إِلَّا مَن شَاءَ اللَّهُ ۖ ثُمَّ نُفِخَ فِيهِ أُخْرَىٰ فَإِذَا هُمْ قِيَامٌ يَنظُرُونَ",
    translation: "Dan ditiuplah sangkakala, maka matilah siapa yang di langit dan di bumi kecuali siapa yang dikehendaki Allah. Kemudian ditiup sangkakala itu sekali lagi, maka tiba-tiba mereka bangun berdiri menunggu (putusan).",
    what_happens: "Malaikat Israfil meniup sangkakala pertama: hancurlah tata surya dan seluruh makhluk binasa. Setelah jeda 40 (masa), sangkakala ditiup kedua kali: arwah kembali ke jasad dan manusia bangkit dari kubur.",
    preparation_guide: "Menyiapkan bekal tauhid murni laa ilaaha illallaah saat sakaratul maut, memperbanyak doa husnul khatimah agar dibangkitkan dalam keadaan diridhai.",
    source_url: "https://quran.com/39/68",
    tags: ["resurrection", "horn", "israfil"]
  },

  // --------------------------------------------------------------------------
  // STAGE 4: PADANG MAHSYAR (AL-HASYR)
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_mahsyar",
    stage_id: "s4_mahsyar",
    stage_num: 4,
    stage_title: "4. Padang Mahsyar (Al-Hasyr)",
    event_code: "MAHSYAR",
    event_name: "Penantian Dahsyat & 7 Golongan Dinaungi Arsy",
    source_type: "hadith",
    reference: "HR. Al-Bukhari No. 660 & Muslim No. 1031",
    grading: "Sahih (Muttafaqun 'Alayh)",
    arabic: "سَبْعَةٌ يُظِلُّهُمُ اللَّهُ فِي ظِلِّهِ يَوْمَ لاَ ظِلَّ إِلاَّ ظِلُّهُ: الإِمَامُ الْعَادِلُ، وَشَابٌّ نَشَأَ فِي عِبَادَةِ رَبِّهِ...",
    translation: "Tujuh golongan yang akan dinaungi Allah di bawah naungan-Nya pada hari tiada naungan selain naungan-Nya: pemimpin yang adil, pemuda yang tumbuh dalam ibadah kepada Tuhannya...",
    what_happens: "Seluruh manusia dikumpulkan di bumi yang rata putih bersih tanpa alas kaki dan tanpa busana. Matahari didekatkan hanya 1 mil sehingga manusia tenggelam dalam keringat sesuai kadar dosanya.",
    preparation_guide: "Mengejar sifat 7 golongan yang dinaungi Arsy: 1. Pemimpin adil. 2. Pemuda taat ibadah. 3. Hati tertambat di masjid. 4. Mencintai karena Allah. 5. Menolak zina karena takut Allah. 6. Sedekah sembunyi-sembunyi. 7. Menangis mengingat Allah saat sendiri.",
    source_url: "https://sunnah.com/bukhari:660",
    tags: ["mahsyar", "shade", "arsy", "sweat"]
  },

  // --------------------------------------------------------------------------
  // STAGE 5: SYAFA'AT 'UZHMA
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_syafaat",
    stage_id: "s5_syafaat",
    stage_num: 5,
    stage_title: "5. Syafa'at 'Uzhma (Al-Maqam Al-Mahmud)",
    event_code: "SYAFAAT",
    event_name: "Sujud Rasulullah ﷺ Membuka Pengadilan Ilahi",
    source_type: "hadith",
    reference: "HR. Al-Bukhari No. 4712 & Muslim No. 194",
    grading: "Sahih (Muttafaqun 'Alayh)",
    arabic: "أَنَا سَيِّدُ النَّاسِ يَوْمَ الْقِيَامَةِ ... فَأَسْجُدُ تَحْتَ الْعَرْشِ فَيَفْتَحُ اللَّهُ عَلَيَّ مِنْ مَحَامِدِهِ",
    translation: "Aku adalah penghulu manusia pada hari kiamat... Maka aku bersujud di bawah Arsy, lalu Allah membukakan bagiku pujian-pujian yang belum pernah diajarkan sebelumnya.",
    what_happens: "Dalam keputusasaan penantian ribuan tahun di Mahsyar, manusia memohon syafa'at kepada Nabi Adam, Nuh, Ibrahim, Musa, dan Isa AS, namun semua menolak hingga mereka datang kepada Nabi Muhammad ﷺ yang bersujud memohon dimulainya hisab.",
    preparation_guide: "Memperbanyak shalawat kepada Nabi ﷺ setiap hari (minimal 100x), membaca doa setelah azan memohon Al-Wasilah dan Al-Fadhilah, serta mengamalkan Sunnah beliau.",
    source_url: "https://sunnah.com/bukhari:4712",
    tags: ["syafaat", "prophet", "intercession"]
  },

  // --------------------------------------------------------------------------
  // STAGE 6: AL-HISAB & PEMBAGIAN KITAB
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_hisab",
    stage_id: "s6_hisab",
    stage_num: 6,
    stage_title: "6. Al-Hisab & Pembagian Kitab Amal",
    event_code: "HISAB",
    event_name: "Pemeriksaan Amal & Kitab Catatan Terbuka",
    source_type: "quran",
    reference: "QS. Al-Insyiqaq: 7-11",
    grading: "Kalamullah (Al-Qur'an Al-Karim)",
    arabic: "فَأَمَّا مَنْ أُوتِيَ كِتَابَهُ بِيَمِينِهِ • فَسَوْفَ يُحَاسَبُ حِسَابًا يَسِيرًا • وَيَنقَلِبُ إِلَىٰ أَهْلِهِ مَسْرُورًا",
    translation: "Adapun orang yang diberikan kitabnya dari sebelah kanannya, maka dia akan dihisab dengan hisab yang mudah, dan dia akan kembali kepada kaumnya dengan gembira.",
    what_happens: "Setiap helai daun amal diperlihatkan. Orang beriman dihisab secara tertutup (Ar-Rakhmah) dan dosanya diampuni. Orang celaka menerima kitab dari sebelah kiri atau belakang punggungnya.",
    preparation_guide: "Melakukan hisab diri (muhasabah) setiap malam sebelum tidur, menutupi aib sesama muslim di dunia agar Allah menutupi aib kita di hadapan mahkamah Mahsyar.",
    source_url: "https://quran.com/84/7",
    tags: ["hisab", "books", "record"]
  },

  // --------------------------------------------------------------------------
  // STAGE 7: AL-MIZAN (TIMBANGAN AMAL)
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_mizan",
    stage_id: "s7_mizan",
    stage_num: 7,
    stage_title: "7. Al-Mizan (Timbangan Hakiki)",
    event_code: "MIZAN",
    event_name: "Penimbangan Amal Kebaikan vs Keburukan",
    source_type: "quran",
    reference: "QS. Al-Anbiya: 47 & HR. Bukhari 6682",
    grading: "Kalamullah / Sahih",
    arabic: "كَلِمَتَانِ حَبِيبَتَانِ إِلَى الرَّحْمَنِ خَفِيفَتَانِ عَلَى اللِّسَانِ ثَقِيلَتَانِ فِي الْمِيزَانِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    translation: "Dua kalimat yang dicintai Ar-Rahman, ringan di lisan, namun sangat berat di timbangan Mizan: 'Subhānallāhi wa bihamdih, Subhānallāhil 'Azhīm'.",
    what_happens: "Timbangan hakiki berskala raksasa dengan dua daun timbangan didirikan. Amal saleh berwujud indah menimbang kebaikan, sedangkan dosa memberatkan sisi keburukan.",
    preparation_guide: "Memperbanyak zikir penimbat mizan (Subhanallah wa bihamdihi Subhanallahil 'Azhim), menjaga akhlak mulia (Husnul Khuluq adalah amalan terberat di mizan), dan bersedekah.",
    source_url: "https://sunnah.com/bukhari:6682",
    tags: ["mizan", "scale", "deeds"]
  },

  // --------------------------------------------------------------------------
  // STAGE 8: AL-HAUDH (TELAGA AL-KAUTSAR)
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_haudh",
    stage_id: "s8_haudh",
    stage_num: 8,
    stage_title: "8. Al-Haudh (Telaga Al-Kautsar)",
    event_code: "HAUDH",
    event_name: "Air Sejuk yang Memadamkan Dahaga Selamanya",
    source_type: "hadith",
    reference: "HR. Al-Bukhari No. 6579 & Muslim No. 2292",
    grading: "Sahih (Muttafaqun 'Alayh)",
    arabic: "حَوْضِي مَسِيرَةُ شَهْرٍ، مَاؤُهُ أَبْيَضُ مِنَ اللَّبَنِ، وَرِيحُهُ أَطْيَبُ مِنَ الْمِسْكِ، وَكِيزَانُهُ كَنُجُومِ السَّمَاءِ، مَنْ شَرِبَ مِنْهَا فَلاَ يَظْمَأُ أَبَدًا",
    translation: "Telagaku seluas perjalanan sebulan, airnya lebih putih dari susu, aromanya lebih harum dari kesturi, bejananya sebanyak bintang di langit. Siapa meminumnya takkan haus selamanya.",
    what_happens: "Rasulullah ﷺ menunggu umatnya di tepi telaga. Orang-orang yang istiqamah meminum air telaga dari tangan mulia beliau. Orang-orang yang murtad atau mengada-adakan bid'ah diusir dari telaga.",
    preparation_guide: "Menjaga kemurnian ajaran Islam tanpa menambah atau mengurangi syariat, istiqamah beramal sunnah, dan memberi minum orang yang kehausan di dunia.",
    source_url: "https://sunnah.com/bukhari:6579",
    tags: ["haudh", "kautsar", "water"]
  },

  // --------------------------------------------------------------------------
  // STAGE 9: ASH-SHIRATH (JEMBATAN DI ATAS JAHANNAM)
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_sirat",
    stage_id: "s9_sirat",
    stage_num: 9,
    stage_title: "9. Ash-Shirath (Jembatan Di Atas Jahannam)",
    event_code: "SHIRATH",
    event_name: "Jembatan Setajam Pedang & Kecepatan Cahaya Iman",
    source_type: "hadith",
    reference: "HR. Muslim No. 195",
    grading: "Sahih",
    arabic: "فَيَمُرُّ أَوَّلُكُمْ كَالْبَرْقِ ... ثُمَّ كَمَرِّ الرِّيحِ ، ثُمَّ كَمَرِّ الطَّيْرِ ... حَتَّى تَجِيءَ أَعْمَالُ الْعِبَادِ فَيَجِيءُ الرَّجُلُ فَلاَ يَسْتَطِيعُ السَّيْرَ إِلاَّ زَحْفًا",
    translation: "Orang pertama dari kalian menyeberang secepat kilat... lalu secepat angin, lalu secepat burung... hingga amal manusia melemah, ada yang menyeberang dengan merangkak.",
    what_happens: "Jembatan dibentangkan di atas Neraka Jahannam yang menyala-nyala. Di sampingnya terdapat besi-besi pencakar (kalalib). Kecepatan dan keselamatan melintas ditentukan 100% oleh cahaya iman dan amal di dunia.",
    preparation_guide: "Menjaga shalat fardhu berjamaah di masjid terutama Subuh dan Isya ('cahaya sempurna di hari kiamat'), menolong kesulitan sesama muslim, dan mempermudah urusan orang lain.",
    source_url: "https://sunnah.com/muslim:195",
    tags: ["shirath", "bridge", "light"]
  },

  // --------------------------------------------------------------------------
  // STAGE 10: AL-QANTHARAH & MUARA ABADI
  // --------------------------------------------------------------------------
  {
    id: "evt_stage_final",
    stage_id: "s10_final",
    stage_num: 10,
    stage_title: "10. Al-Qantharah & Muara Abadi (Surga / Neraka)",
    event_code: "SURGA",
    event_name: "Pembersihan Hati & Pintu Kenikmatan Abadi",
    source_type: "hadith",
    reference: "HR. Al-Bukhari No. 6535",
    grading: "Sahih",
    arabic: "يَخْلُصُ الْمُؤْمِنُونَ مِنَ النَّارِ فَيُحْبَسُونَ عَلَى قَنْطَرَةٍ بَيْنَ الْجَنَّةِ وَالنَّارِ فَيُقْتَصُّ لِبَعْضِهِمْ مِنْ بَعْضٍ مَظَالِمُ",
    translation: "Orang-orang beriman selamat dari neraka, lalu ditahan di jembatan (Qantharah) antara surga dan neraka, lalu diselesaikan kezaliman di antara mereka sampai bersih murni masuk surga.",
    what_happens: "Hati orang beriman dibersihkan dari sisa kedengkian. Pintu-pintu Surga dibuka menyambut mereka dengan salam kedamaian, kekal dalam kenikmatan abadi melihat Wajah Allah Ta'ala.",
    preparation_guide: "Saling memaafkan sebelum ajal tiba, melunasi hutang, ridha atas ketentuan takdir, dan memohon Surga Firdaus (Allāhumma innī as'alukal jannah wa a'ūdzu bika minan nār).",
    source_url: "https://sunnah.com/bukhari:6535",
    tags: ["qantharah", "paradise", "eternity"]
  }
];

